/* Dialog.c generated by valac 0.50.2, the Vala compiler
 * generated from Dialog.vala, do not modify */

/*
 * Copyright (C) 2020-2021 Lains
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include <adwaita.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <glib/gi18n-lib.h>

#define KHRONOS_TYPE_MAIN_WINDOW (khronos_main_window_get_type ())
#define KHRONOS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindow))
#define KHRONOS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindowClass))
#define KHRONOS_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_MAIN_WINDOW))
#define KHRONOS_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_MAIN_WINDOW))
#define KHRONOS_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindowClass))

typedef struct _KhronosMainWindow KhronosMainWindow;
typedef struct _KhronosMainWindowClass KhronosMainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _KhronosDialogDisplaySaveDialogData KhronosDialogDisplaySaveDialogData;
typedef struct _Block1Data Block1Data;
typedef struct _KhronosDialogRunDialogAsyncData KhronosDialogRunDialogAsyncData;

struct _KhronosDialogDisplaySaveDialogData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	GFile* result;
	GtkFileChooserNative* chooser;
	KhronosMainWindow* _tmp0_;
	GtkFileChooserNative* _tmp1_;
	GtkFileChooserNative* _tmp2_;
	KhronosMainWindow* _tmp3_;
	GtkFileFilter* filter1;
	GtkFileFilter* _tmp4_;
	GtkFileFilter* _tmp5_;
	GtkFileFilter* _tmp6_;
	GtkFileChooserNative* _tmp7_;
	GtkFileFilter* _tmp8_;
	GtkFileFilter* filter;
	GtkFileFilter* _tmp9_;
	GtkFileFilter* _tmp10_;
	GtkFileFilter* _tmp11_;
	GtkFileChooserNative* _tmp12_;
	GtkFileFilter* _tmp13_;
	GtkResponseType response;
	GtkFileChooserNative* _tmp14_;
	GtkResponseType _tmp15_;
	GtkFileChooserNative* _tmp16_;
	GFile* _tmp17_;
};

struct _Block1Data {
	int _ref_count_;
	GtkResponseType response;
	gpointer _async_data_;
};

struct _KhronosDialogRunDialogAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	GtkFileChooserNative* dialog;
	GtkResponseType result;
	Block1Data* _data1_;
};

extern KhronosMainWindow* khronos_dialog_win;
KhronosMainWindow* khronos_dialog_win = NULL;

GType khronos_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosMainWindow, g_object_unref)
static void khronos_dialog_display_save_dialog_data_free (gpointer _data);
void khronos_dialog_display_save_dialog (GAsyncReadyCallback _callback_,
                                         gpointer _user_data_);
GFile* khronos_dialog_display_save_dialog_finish (GAsyncResult* _res_);
static gboolean khronos_dialog_display_save_dialog_co (KhronosDialogDisplaySaveDialogData* _data_);
void khronos_dialog_run_dialog_async (GtkFileChooserNative* dialog,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_);
GtkResponseType khronos_dialog_run_dialog_finish (GAsyncResult* _res_);
static void khronos_dialog_display_save_dialog_ready (GObject* source_object,
                                               GAsyncResult* _res_,
                                               gpointer _user_data_);
static void khronos_dialog_run_dialog_async_data_free (gpointer _data);
static gboolean khronos_dialog_run_dialog_async_co (KhronosDialogRunDialogAsyncData* _data_);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_,
                 gint r);
static void ___lambda4__gtk_native_dialog_response (GtkNativeDialog* _sender,
                                             gint response_id,
                                             gpointer self);

static void
khronos_dialog_display_save_dialog_data_free (gpointer _data)
{
	KhronosDialogDisplaySaveDialogData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->result);
	g_slice_free (KhronosDialogDisplaySaveDialogData, _data_);
}

void
khronos_dialog_display_save_dialog (GAsyncReadyCallback _callback_,
                                    gpointer _user_data_)
{
	KhronosDialogDisplaySaveDialogData* _data_;
	_data_ = g_slice_new0 (KhronosDialogDisplaySaveDialogData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, khronos_dialog_display_save_dialog_data_free);
	khronos_dialog_display_save_dialog_co (_data_);
}

GFile*
khronos_dialog_display_save_dialog_finish (GAsyncResult* _res_)
{
	GFile* result;
	KhronosDialogDisplaySaveDialogData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
khronos_dialog_display_save_dialog_ready (GObject* source_object,
                                          GAsyncResult* _res_,
                                          gpointer _user_data_)
{
	KhronosDialogDisplaySaveDialogData* _data_;
#line 31 "../src/Services/Dialog.vala"
	_data_ = _user_data_;
#line 31 "../src/Services/Dialog.vala"
	_data_->_source_object_ = source_object;
#line 31 "../src/Services/Dialog.vala"
	_data_->_res_ = _res_;
#line 31 "../src/Services/Dialog.vala"
	khronos_dialog_display_save_dialog_co (_data_);
#line 161 "Dialog.c"
}

static gboolean
khronos_dialog_display_save_dialog_co (KhronosDialogDisplaySaveDialogData* _data_)
{
#line 19 "../src/Services/Dialog.vala"
	switch (_data_->_state_) {
#line 19 "../src/Services/Dialog.vala"
		case 0:
#line 171 "Dialog.c"
		goto _state_0;
#line 19 "../src/Services/Dialog.vala"
		case 1:
#line 175 "Dialog.c"
		goto _state_1;
		default:
#line 19 "../src/Services/Dialog.vala"
		g_assert_not_reached ();
#line 180 "Dialog.c"
	}
	_state_0:
#line 20 "../src/Services/Dialog.vala"
	_data_->_tmp0_ = khronos_dialog_win;
#line 20 "../src/Services/Dialog.vala"
	_data_->_tmp1_ = gtk_file_chooser_native_new (NULL, (GtkWindow*) _data_->_tmp0_, GTK_FILE_CHOOSER_ACTION_SAVE, NULL, NULL);
#line 20 "../src/Services/Dialog.vala"
	_data_->chooser = _data_->_tmp1_;
#line 21 "../src/Services/Dialog.vala"
	_data_->_tmp2_ = _data_->chooser;
#line 21 "../src/Services/Dialog.vala"
	_data_->_tmp3_ = khronos_dialog_win;
#line 21 "../src/Services/Dialog.vala"
	gtk_native_dialog_set_transient_for ((GtkNativeDialog*) _data_->_tmp2_, (GtkWindow*) _data_->_tmp3_);
#line 22 "../src/Services/Dialog.vala"
	_data_->_tmp4_ = gtk_file_filter_new ();
#line 22 "../src/Services/Dialog.vala"
	_data_->filter1 = _data_->_tmp4_;
#line 23 "../src/Services/Dialog.vala"
	_data_->_tmp5_ = _data_->filter1;
#line 23 "../src/Services/Dialog.vala"
	gtk_file_filter_set_name (_data_->_tmp5_, _ ("CSV files"));
#line 24 "../src/Services/Dialog.vala"
	_data_->_tmp6_ = _data_->filter1;
#line 24 "../src/Services/Dialog.vala"
	gtk_file_filter_add_pattern (_data_->_tmp6_, "*.csv");
#line 25 "../src/Services/Dialog.vala"
	_data_->_tmp7_ = _data_->chooser;
#line 25 "../src/Services/Dialog.vala"
	_data_->_tmp8_ = _data_->filter1;
#line 25 "../src/Services/Dialog.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) _data_->_tmp7_, _data_->_tmp8_);
#line 26 "../src/Services/Dialog.vala"
	_data_->_tmp9_ = gtk_file_filter_new ();
#line 26 "../src/Services/Dialog.vala"
	_data_->filter = _data_->_tmp9_;
#line 27 "../src/Services/Dialog.vala"
	_data_->_tmp10_ = _data_->filter;
#line 27 "../src/Services/Dialog.vala"
	gtk_file_filter_set_name (_data_->_tmp10_, _ ("All files"));
#line 28 "../src/Services/Dialog.vala"
	_data_->_tmp11_ = _data_->filter;
#line 28 "../src/Services/Dialog.vala"
	gtk_file_filter_add_pattern (_data_->_tmp11_, "*");
#line 29 "../src/Services/Dialog.vala"
	_data_->_tmp12_ = _data_->chooser;
#line 29 "../src/Services/Dialog.vala"
	_data_->_tmp13_ = _data_->filter;
#line 29 "../src/Services/Dialog.vala"
	gtk_file_chooser_add_filter ((GtkFileChooser*) _data_->_tmp12_, _data_->_tmp13_);
#line 31 "../src/Services/Dialog.vala"
	_data_->_tmp14_ = _data_->chooser;
#line 31 "../src/Services/Dialog.vala"
	_data_->_state_ = 1;
#line 31 "../src/Services/Dialog.vala"
	khronos_dialog_run_dialog_async (_data_->_tmp14_, khronos_dialog_display_save_dialog_ready, _data_);
#line 31 "../src/Services/Dialog.vala"
	return FALSE;
#line 239 "Dialog.c"
	_state_1:
#line 31 "../src/Services/Dialog.vala"
	_data_->response = khronos_dialog_run_dialog_finish (_data_->_res_);
#line 33 "../src/Services/Dialog.vala"
	_data_->_tmp15_ = _data_->response;
#line 33 "../src/Services/Dialog.vala"
	if (_data_->_tmp15_ == GTK_RESPONSE_ACCEPT) {
#line 34 "../src/Services/Dialog.vala"
		_data_->_tmp16_ = _data_->chooser;
#line 34 "../src/Services/Dialog.vala"
		_data_->_tmp17_ = gtk_file_chooser_get_file ((GtkFileChooser*) _data_->_tmp16_);
#line 34 "../src/Services/Dialog.vala"
		_data_->result = _data_->_tmp17_;
#line 34 "../src/Services/Dialog.vala"
		_g_object_unref0 (_data_->filter);
#line 34 "../src/Services/Dialog.vala"
		_g_object_unref0 (_data_->filter1);
#line 34 "../src/Services/Dialog.vala"
		_g_object_unref0 (_data_->chooser);
#line 34 "../src/Services/Dialog.vala"
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 34 "../src/Services/Dialog.vala"
		if (_data_->_state_ != 0) {
#line 34 "../src/Services/Dialog.vala"
			while (!g_task_get_completed (_data_->_async_result)) {
#line 34 "../src/Services/Dialog.vala"
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 267 "Dialog.c"
			}
		}
#line 34 "../src/Services/Dialog.vala"
		g_object_unref (_data_->_async_result);
#line 34 "../src/Services/Dialog.vala"
		return FALSE;
#line 274 "Dialog.c"
	}
#line 37 "../src/Services/Dialog.vala"
	_data_->result = NULL;
#line 37 "../src/Services/Dialog.vala"
	_g_object_unref0 (_data_->filter);
#line 37 "../src/Services/Dialog.vala"
	_g_object_unref0 (_data_->filter1);
#line 37 "../src/Services/Dialog.vala"
	_g_object_unref0 (_data_->chooser);
#line 37 "../src/Services/Dialog.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 37 "../src/Services/Dialog.vala"
	if (_data_->_state_ != 0) {
#line 37 "../src/Services/Dialog.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 37 "../src/Services/Dialog.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 292 "Dialog.c"
		}
	}
#line 37 "../src/Services/Dialog.vala"
	g_object_unref (_data_->_async_result);
#line 37 "../src/Services/Dialog.vala"
	return FALSE;
#line 299 "Dialog.c"
}

static void
khronos_dialog_run_dialog_async_data_free (gpointer _data)
{
	KhronosDialogRunDialogAsyncData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->dialog);
	g_slice_free (KhronosDialogRunDialogAsyncData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
khronos_dialog_run_dialog_async (GtkFileChooserNative* dialog,
                                 GAsyncReadyCallback _callback_,
                                 gpointer _user_data_)
{
	KhronosDialogRunDialogAsyncData* _data_;
	GtkFileChooserNative* _tmp0_;
	g_return_if_fail (dialog != NULL);
	_data_ = g_slice_new0 (KhronosDialogRunDialogAsyncData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, khronos_dialog_run_dialog_async_data_free);
	_tmp0_ = _g_object_ref0 (dialog);
	_g_object_unref0 (_data_->dialog);
	_data_->dialog = _tmp0_;
	khronos_dialog_run_dialog_async_co (_data_);
}

GtkResponseType
khronos_dialog_run_dialog_finish (GAsyncResult* _res_)
{
	GtkResponseType result;
	KhronosDialogRunDialogAsyncData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	return result;
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 40 "../src/Services/Dialog.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 40 "../src/Services/Dialog.vala"
	return _data1_;
#line 351 "Dialog.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 40 "../src/Services/Dialog.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 40 "../src/Services/Dialog.vala"
		g_slice_free (Block1Data, _data1_);
#line 363 "Dialog.c"
	}
}

static void
__lambda4_ (Block1Data* _data1_,
            gint r)
{
#line 44 "../src/Services/Dialog.vala"
	_data1_->response = (GtkResponseType) r;
#line 46 "../src/Services/Dialog.vala"
	khronos_dialog_run_dialog_async_co (_data1_->_async_data_);
#line 375 "Dialog.c"
}

static void
___lambda4__gtk_native_dialog_response (GtkNativeDialog* _sender,
                                        gint response_id,
                                        gpointer self)
{
#line 43 "../src/Services/Dialog.vala"
	__lambda4_ (self, response_id);
#line 385 "Dialog.c"
}

static gboolean
khronos_dialog_run_dialog_async_co (KhronosDialogRunDialogAsyncData* _data_)
{
#line 40 "../src/Services/Dialog.vala"
	switch (_data_->_state_) {
#line 40 "../src/Services/Dialog.vala"
		case 0:
#line 395 "Dialog.c"
		goto _state_0;
#line 40 "../src/Services/Dialog.vala"
		case 1:
#line 399 "Dialog.c"
		goto _state_1;
		default:
#line 40 "../src/Services/Dialog.vala"
		g_assert_not_reached ();
#line 404 "Dialog.c"
	}
	_state_0:
#line 40 "../src/Services/Dialog.vala"
	_data_->_data1_ = g_slice_new0 (Block1Data);
#line 40 "../src/Services/Dialog.vala"
	_data_->_data1_->_ref_count_ = 1;
#line 40 "../src/Services/Dialog.vala"
	_data_->_data1_->_async_data_ = _data_;
#line 41 "../src/Services/Dialog.vala"
	_data_->_data1_->response = GTK_RESPONSE_CANCEL;
#line 43 "../src/Services/Dialog.vala"
	g_signal_connect_data ((GtkNativeDialog*) _data_->dialog, "response", (GCallback) ___lambda4__gtk_native_dialog_response, block1_data_ref (_data_->_data1_), (GClosureNotify) block1_data_unref, 0);
#line 49 "../src/Services/Dialog.vala"
	gtk_native_dialog_show ((GtkNativeDialog*) _data_->dialog);
#line 51 "../src/Services/Dialog.vala"
	_data_->_state_ = 1;
#line 51 "../src/Services/Dialog.vala"
	return FALSE;
#line 423 "Dialog.c"
	_state_1:
	;
#line 52 "../src/Services/Dialog.vala"
	_data_->result = _data_->_data1_->response;
#line 52 "../src/Services/Dialog.vala"
	block1_data_unref (_data_->_data1_);
#line 52 "../src/Services/Dialog.vala"
	_data_->_data1_ = NULL;
#line 52 "../src/Services/Dialog.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 52 "../src/Services/Dialog.vala"
	if (_data_->_state_ != 0) {
#line 52 "../src/Services/Dialog.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 52 "../src/Services/Dialog.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 440 "Dialog.c"
		}
	}
#line 52 "../src/Services/Dialog.vala"
	g_object_unref (_data_->_async_result);
#line 52 "../src/Services/Dialog.vala"
	return FALSE;
#line 447 "Dialog.c"
}

