/* FileManager.c generated by valac 0.50.2, the Vala compiler
 * generated from FileManager.vala, do not modify */

#include <gio/gio.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>
#include <glib/gstdio.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define KHRONOS_TYPE_LOG (khronos_log_get_type ())
#define KHRONOS_LOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_LOG, KhronosLog))
#define KHRONOS_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_LOG, KhronosLogClass))
#define KHRONOS_IS_LOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_LOG))
#define KHRONOS_IS_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_LOG))
#define KHRONOS_LOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_LOG, KhronosLogClass))

typedef struct _KhronosLog KhronosLog;
typedef struct _KhronosLogClass KhronosLogClass;
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef struct _KhronosFileManagerSaveAsData KhronosFileManagerSaveAsData;

struct _KhronosFileManagerSaveAsData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	GListStore* liststore;
	gchar* tasks;
	gchar* _tmp0_;
	GFile* file;
	GFile* _tmp1_;
	guint i;
	guint n;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gboolean _tmp4_;
	guint _tmp5_;
	GObject* item;
	GObject* _tmp6_;
	const gchar* _tmp7_;
	GObject* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	GObject* _tmp17_;
	const gchar* _tmp18_;
	const gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	GFile* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	const gchar* _tmp34_;
	GError* _inner_error0_;
};

static void khronos_file_manager_save_as_data_free (gpointer _data);
void khronos_file_manager_save_as (GListStore* liststore,
                                   GAsyncReadyCallback _callback_,
                                   gpointer _user_data_);
void khronos_file_manager_save_as_finish (GAsyncResult* _res_,
                                          GError** error);
static gboolean khronos_file_manager_save_as_co (KhronosFileManagerSaveAsData* _data_);
void khronos_dialog_display_save_dialog (GAsyncReadyCallback _callback_,
                                         gpointer _user_data_);
GFile* khronos_dialog_display_save_dialog_finish (GAsyncResult* _res_);
static void khronos_file_manager_save_as_ready (GObject* source_object,
                                         GAsyncResult* _res_,
                                         gpointer _user_data_);
GType khronos_log_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosLog, g_object_unref)
const gchar* khronos_log_get_name (KhronosLog* self);
const gchar* khronos_log_get_timedate (KhronosLog* self);

static void
khronos_file_manager_save_as_data_free (gpointer _data)
{
	KhronosFileManagerSaveAsData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->liststore);
	g_slice_free (KhronosFileManagerSaveAsData, _data_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
khronos_file_manager_save_as (GListStore* liststore,
                              GAsyncReadyCallback _callback_,
                              gpointer _user_data_)
{
	KhronosFileManagerSaveAsData* _data_;
	GListStore* _tmp0_;
	g_return_if_fail (liststore != NULL);
	_data_ = g_slice_new0 (KhronosFileManagerSaveAsData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, khronos_file_manager_save_as_data_free);
	_tmp0_ = _g_object_ref0 (liststore);
	_g_object_unref0 (_data_->liststore);
	_data_->liststore = _tmp0_;
	khronos_file_manager_save_as_co (_data_);
}

void
khronos_file_manager_save_as_finish (GAsyncResult* _res_,
                                     GError** error)
{
	KhronosFileManagerSaveAsData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), error);
	if (NULL == _data_) {
		return;
	}
}

static void
khronos_file_manager_save_as_ready (GObject* source_object,
                                    GAsyncResult* _res_,
                                    gpointer _user_data_)
{
	KhronosFileManagerSaveAsData* _data_;
#line 4 "../src/Services/FileManager.vala"
	_data_ = _user_data_;
#line 4 "../src/Services/FileManager.vala"
	_data_->_source_object_ = source_object;
#line 4 "../src/Services/FileManager.vala"
	_data_->_res_ = _res_;
#line 4 "../src/Services/FileManager.vala"
	khronos_file_manager_save_as_co (_data_);
#line 151 "FileManager.c"
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result = NULL;
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1535 "glib-2.0.vapi"
	if ((*((gchar*) self)) == '\0') {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 173 "FileManager.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = (*((gchar*) old)) == '\0';
#line 177 "FileManager.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp1_) {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = TRUE;
#line 183 "FileManager.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
#line 187 "FileManager.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp0_) {
#line 191 "FileManager.c"
		gchar* _tmp2_;
#line 1536 "glib-2.0.vapi"
		_tmp2_ = g_strdup (self);
#line 1536 "glib-2.0.vapi"
		result = _tmp2_;
#line 1536 "glib-2.0.vapi"
		return result;
#line 199 "FileManager.c"
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 1539 "glib-2.0.vapi"
		_tmp3_ = g_regex_escape_string (old, -1);
#line 1539 "glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1539 "glib-2.0.vapi"
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
#line 1539 "glib-2.0.vapi"
		_tmp6_ = _tmp5_;
#line 1539 "glib-2.0.vapi"
		_g_free0 (_tmp4_);
#line 1539 "glib-2.0.vapi"
		regex = _tmp6_;
#line 1539 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1539 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 227 "FileManager.c"
				goto __catch0_g_regex_error;
			}
#line 1539 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1539 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1539 "glib-2.0.vapi"
			return NULL;
#line 236 "FileManager.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp8_ = regex;
#line 1540 "glib-2.0.vapi"
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
#line 1540 "glib-2.0.vapi"
		_tmp7_ = _tmp9_;
#line 1540 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1540 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 250 "FileManager.c"
				goto __catch0_g_regex_error;
			}
#line 1540 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1540 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1540 "glib-2.0.vapi"
			return NULL;
#line 259 "FileManager.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp10_ = _tmp7_;
#line 1540 "glib-2.0.vapi"
		_tmp7_ = NULL;
#line 1540 "glib-2.0.vapi"
		result = _tmp10_;
#line 1540 "glib-2.0.vapi"
		_g_free0 (_tmp7_);
#line 1540 "glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
		return result;
#line 273 "FileManager.c"
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
#line 1538 "glib-2.0.vapi"
		g_clear_error (&_inner_error0_);
#line 1542 "glib-2.0.vapi"
		g_assert_not_reached ();
#line 282 "FileManager.c"
	}
	__finally0:
#line 1538 "glib-2.0.vapi"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1538 "glib-2.0.vapi"
	g_clear_error (&_inner_error0_);
#line 1538 "glib-2.0.vapi"
	return NULL;
#line 291 "FileManager.c"
}

static gboolean
khronos_file_manager_save_as_co (KhronosFileManagerSaveAsData* _data_)
{
#line 2 "../src/Services/FileManager.vala"
	switch (_data_->_state_) {
#line 2 "../src/Services/FileManager.vala"
		case 0:
#line 301 "FileManager.c"
		goto _state_0;
#line 2 "../src/Services/FileManager.vala"
		case 1:
#line 305 "FileManager.c"
		goto _state_1;
		default:
#line 2 "../src/Services/FileManager.vala"
		g_assert_not_reached ();
#line 310 "FileManager.c"
	}
	_state_0:
#line 3 "../src/Services/FileManager.vala"
	_data_->_tmp0_ = g_strdup ("");
#line 3 "../src/Services/FileManager.vala"
	_data_->tasks = _data_->_tmp0_;
#line 4 "../src/Services/FileManager.vala"
	_data_->_state_ = 1;
#line 4 "../src/Services/FileManager.vala"
	khronos_dialog_display_save_dialog (khronos_file_manager_save_as_ready, _data_);
#line 4 "../src/Services/FileManager.vala"
	return FALSE;
#line 323 "FileManager.c"
	_state_1:
#line 4 "../src/Services/FileManager.vala"
	_data_->_tmp1_ = khronos_dialog_display_save_dialog_finish (_data_->_res_);
#line 4 "../src/Services/FileManager.vala"
	_data_->file = _data_->_tmp1_;
#line 5 "../src/Services/FileManager.vala"
	_data_->n = g_list_model_get_n_items ((GListModel*) _data_->liststore);
#line 7 "../src/Services/FileManager.vala"
	_data_->_tmp2_ = _data_->tasks;
#line 7 "../src/Services/FileManager.vala"
	_data_->_tmp3_ = g_strconcat (_data_->_tmp2_, "task,timedate\n", NULL);
#line 7 "../src/Services/FileManager.vala"
	_g_free0 (_data_->tasks);
#line 7 "../src/Services/FileManager.vala"
	_data_->tasks = _data_->_tmp3_;
#line 339 "FileManager.c"
	{
#line 8 "../src/Services/FileManager.vala"
		_data_->i = (guint) 0;
#line 8 "../src/Services/FileManager.vala"
		_data_->_tmp4_ = TRUE;
#line 8 "../src/Services/FileManager.vala"
		while (TRUE) {
#line 8 "../src/Services/FileManager.vala"
			if (!_data_->_tmp4_) {
#line 8 "../src/Services/FileManager.vala"
				_data_->_tmp5_ = _data_->i;
#line 8 "../src/Services/FileManager.vala"
				_data_->i = _data_->_tmp5_ + 1;
#line 353 "FileManager.c"
			}
#line 8 "../src/Services/FileManager.vala"
			_data_->_tmp4_ = FALSE;
#line 8 "../src/Services/FileManager.vala"
			if (!(_data_->i < _data_->n)) {
#line 8 "../src/Services/FileManager.vala"
				break;
#line 361 "FileManager.c"
			}
#line 9 "../src/Services/FileManager.vala"
			_data_->_tmp6_ = g_list_model_get_item ((GListModel*) _data_->liststore, _data_->i);
#line 9 "../src/Services/FileManager.vala"
			_data_->item = _data_->_tmp6_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp7_ = _data_->tasks;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp8_ = _data_->item;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp9_ = khronos_log_get_name (G_TYPE_CHECK_INSTANCE_CAST (_data_->_tmp8_, KHRONOS_TYPE_LOG, KhronosLog));
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp10_ = _data_->_tmp9_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp11_ = string_replace (_data_->_tmp10_, "\"", "");
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp12_ = _data_->_tmp11_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp13_ = g_strconcat ("\"", _data_->_tmp12_, NULL);
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp14_ = _data_->_tmp13_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp15_ = g_strconcat (_data_->_tmp14_, "\",\"", NULL);
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp16_ = _data_->_tmp15_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp17_ = _data_->item;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp18_ = khronos_log_get_timedate (G_TYPE_CHECK_INSTANCE_CAST (_data_->_tmp17_, KHRONOS_TYPE_LOG, KhronosLog));
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp19_ = _data_->_tmp18_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp20_ = string_replace (_data_->_tmp19_, "\"", "");
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp21_ = _data_->_tmp20_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp22_ = string_replace (_data_->_tmp21_, "<span font_features=\'tnum\'>", "");
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp23_ = _data_->_tmp22_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp24_ = string_replace (_data_->_tmp23_, "</span>", "");
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp25_ = _data_->_tmp24_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp26_ = g_strconcat (_data_->_tmp16_, _data_->_tmp25_, NULL);
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp27_ = _data_->_tmp26_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp28_ = g_strconcat (_data_->_tmp27_, "\"\n", NULL);
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp29_ = _data_->_tmp28_;
#line 10 "../src/Services/FileManager.vala"
			_data_->_tmp30_ = g_strconcat (_data_->_tmp7_, _data_->_tmp29_, NULL);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->tasks);
#line 10 "../src/Services/FileManager.vala"
			_data_->tasks = _data_->_tmp30_;
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp29_);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp27_);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp25_);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp23_);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp21_);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp16_);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp14_);
#line 10 "../src/Services/FileManager.vala"
			_g_free0 (_data_->_tmp12_);
#line 8 "../src/Services/FileManager.vala"
			_g_object_unref0 (_data_->item);
#line 437 "FileManager.c"
		}
	}
#line 16 "../src/Services/FileManager.vala"
	_data_->_tmp31_ = _data_->file;
#line 16 "../src/Services/FileManager.vala"
	_data_->_tmp32_ = g_file_get_path (_data_->_tmp31_);
#line 16 "../src/Services/FileManager.vala"
	_data_->_tmp33_ = _data_->_tmp32_;
#line 16 "../src/Services/FileManager.vala"
	_data_->_tmp34_ = _data_->tasks;
#line 16 "../src/Services/FileManager.vala"
	g_file_set_contents (_data_->_tmp33_, _data_->_tmp34_, (gssize) -1, &_data_->_inner_error0_);
#line 16 "../src/Services/FileManager.vala"
	_g_free0 (_data_->_tmp33_);
#line 16 "../src/Services/FileManager.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 16 "../src/Services/FileManager.vala"
		g_task_return_error (_data_->_async_result, _data_->_inner_error0_);
#line 16 "../src/Services/FileManager.vala"
		_g_object_unref0 (_data_->file);
#line 16 "../src/Services/FileManager.vala"
		_g_free0 (_data_->tasks);
#line 16 "../src/Services/FileManager.vala"
		g_object_unref (_data_->_async_result);
#line 16 "../src/Services/FileManager.vala"
		return FALSE;
#line 464 "FileManager.c"
	}
#line 17 "../src/Services/FileManager.vala"
	g_debug ("FileManager.vala:17: Save as button pressed.");
#line 2 "../src/Services/FileManager.vala"
	_g_object_unref0 (_data_->file);
#line 2 "../src/Services/FileManager.vala"
	_g_free0 (_data_->tasks);
#line 2 "../src/Services/FileManager.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 2 "../src/Services/FileManager.vala"
	if (_data_->_state_ != 0) {
#line 2 "../src/Services/FileManager.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 2 "../src/Services/FileManager.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 480 "FileManager.c"
		}
	}
#line 2 "../src/Services/FileManager.vala"
	g_object_unref (_data_->_async_result);
#line 2 "../src/Services/FileManager.vala"
	return FALSE;
#line 487 "FileManager.c"
}

