/* TaskManager.c generated by valac 0.50.2, the Vala compiler
 * generated from TaskManager.vala, do not modify */

/*
* Copyright (c) 2020-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <glib-object.h>
#include <adwaita.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <gobject/gvaluecollector.h>

#define KHRONOS_TYPE_TASK_MANAGER (khronos_task_manager_get_type ())
#define KHRONOS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_TASK_MANAGER, KhronosTaskManager))
#define KHRONOS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_TASK_MANAGER, KhronosTaskManagerClass))
#define KHRONOS_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_TASK_MANAGER))
#define KHRONOS_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_TASK_MANAGER))
#define KHRONOS_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_TASK_MANAGER, KhronosTaskManagerClass))

typedef struct _KhronosTaskManager KhronosTaskManager;
typedef struct _KhronosTaskManagerClass KhronosTaskManagerClass;
typedef struct _KhronosTaskManagerPrivate KhronosTaskManagerPrivate;

#define KHRONOS_TYPE_MAIN_WINDOW (khronos_main_window_get_type ())
#define KHRONOS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindow))
#define KHRONOS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindowClass))
#define KHRONOS_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_MAIN_WINDOW))
#define KHRONOS_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_MAIN_WINDOW))
#define KHRONOS_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindowClass))

typedef struct _KhronosMainWindow KhronosMainWindow;
typedef struct _KhronosMainWindowClass KhronosMainWindowClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define KHRONOS_TYPE_LOG (khronos_log_get_type ())
#define KHRONOS_LOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_LOG, KhronosLog))
#define KHRONOS_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_LOG, KhronosLogClass))
#define KHRONOS_IS_LOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_LOG))
#define KHRONOS_IS_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_LOG))
#define KHRONOS_LOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_LOG, KhronosLogClass))

typedef struct _KhronosLog KhronosLog;
typedef struct _KhronosLogClass KhronosLogClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
typedef struct _KhronosParamSpecTaskManager KhronosParamSpecTaskManager;

struct _KhronosTaskManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	KhronosTaskManagerPrivate * priv;
	KhronosMainWindow* win;
	JsonBuilder* builder;
};

struct _KhronosTaskManagerClass {
	GTypeClass parent_class;
	void (*finalize) (KhronosTaskManager *self);
};

struct _KhronosTaskManagerPrivate {
	gchar* app_dir;
	gchar* file_name;
};

struct _KhronosParamSpecTaskManager {
	GParamSpec parent_instance;
};

static gint KhronosTaskManager_private_offset;
static gpointer khronos_task_manager_parent_class = NULL;

gpointer khronos_task_manager_ref (gpointer instance);
void khronos_task_manager_unref (gpointer instance);
GParamSpec* khronos_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void khronos_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void khronos_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer khronos_value_get_task_manager (const GValue* value);
GType khronos_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosTaskManager, khronos_task_manager_unref)
GType khronos_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosMainWindow, g_object_unref)
KhronosTaskManager* khronos_task_manager_new (KhronosMainWindow* win);
KhronosTaskManager* khronos_task_manager_construct (GType object_type,
                                                    KhronosMainWindow* win);
void khronos_task_manager_save_to_file (KhronosTaskManager* self,
                                        GListStore* liststore);
GType khronos_log_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosLog, g_object_unref)
const gchar* khronos_log_get_name (KhronosLog* self);
const gchar* khronos_log_get_timedate (KhronosLog* self);
static void _vala_JsonNode_free (JsonNode* self);
void khronos_task_manager_load_from_file (KhronosTaskManager* self);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
void khronos_main_window_add_task (KhronosMainWindow* self,
                                   const gchar* name,
                                   const gchar* timedate);
static void khronos_task_manager_finalize (KhronosTaskManager * obj);
static GType khronos_task_manager_get_type_once (void);

static inline gpointer
khronos_task_manager_get_instance_private (KhronosTaskManager* self)
{
	return G_STRUCT_MEMBER_P (self, KhronosTaskManager_private_offset);
}

KhronosTaskManager*
khronos_task_manager_construct (GType object_type,
                                KhronosMainWindow* win)
{
	KhronosTaskManager* self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
#line 28 "../src/Services/TaskManager.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 28 "../src/Services/TaskManager.vala"
	self = (KhronosTaskManager*) g_type_create_instance (object_type);
#line 29 "../src/Services/TaskManager.vala"
	self->win = win;
#line 30 "../src/Services/TaskManager.vala"
	_tmp0_ = self->priv->app_dir;
#line 30 "../src/Services/TaskManager.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/saved_logged_tasks.json", NULL);
#line 30 "../src/Services/TaskManager.vala"
	_g_free0 (self->priv->file_name);
#line 30 "../src/Services/TaskManager.vala"
	self->priv->file_name = _tmp1_;
#line 31 "../src/Services/TaskManager.vala"
	_tmp2_ = self->priv->file_name;
#line 31 "../src/Services/TaskManager.vala"
	_tmp3_ = g_strdup_printf ("%s", _tmp2_);
#line 31 "../src/Services/TaskManager.vala"
	_tmp4_ = _tmp3_;
#line 31 "../src/Services/TaskManager.vala"
	g_debug ("TaskManager.vala:31: %s", _tmp4_);
#line 31 "../src/Services/TaskManager.vala"
	_g_free0 (_tmp4_);
#line 28 "../src/Services/TaskManager.vala"
	return self;
#line 172 "TaskManager.c"
}

KhronosTaskManager*
khronos_task_manager_new (KhronosMainWindow* win)
{
#line 28 "../src/Services/TaskManager.vala"
	return khronos_task_manager_construct (KHRONOS_TYPE_TASK_MANAGER, win);
#line 180 "TaskManager.c"
}

static void
_vala_JsonNode_free (JsonNode* self)
{
#line 57 "../src/Services/TaskManager.vala"
	g_boxed_free (json_node_get_type (), self);
#line 188 "TaskManager.c"
}

void
khronos_task_manager_save_to_file (KhronosTaskManager* self,
                                   GListStore* liststore)
{
	gchar* json_string = NULL;
	gchar* _tmp0_;
	JsonBuilder* b = NULL;
	JsonBuilder* _tmp1_;
	JsonBuilder* _tmp2_;
	JsonBuilder* _tmp3_;
	guint i = 0U;
	guint n = 0U;
	JsonBuilder* _tmp17_;
	JsonGenerator* generator = NULL;
	JsonGenerator* _tmp18_;
	JsonNode* root = NULL;
	JsonBuilder* _tmp19_;
	JsonNode* _tmp20_;
	JsonGenerator* _tmp21_;
	JsonNode* _tmp22_;
	JsonGenerator* _tmp23_;
	gchar* _tmp24_;
	GFile* dir = NULL;
	const gchar* _tmp25_;
	GFile* _tmp26_;
	GFile* file = NULL;
	const gchar* _tmp27_;
	GFile* _tmp28_;
	GError* _inner_error0_ = NULL;
#line 34 "../src/Services/TaskManager.vala"
	g_return_if_fail (self != NULL);
#line 34 "../src/Services/TaskManager.vala"
	g_return_if_fail (liststore != NULL);
#line 35 "../src/Services/TaskManager.vala"
	_tmp0_ = g_strdup ("");
#line 35 "../src/Services/TaskManager.vala"
	json_string = _tmp0_;
#line 36 "../src/Services/TaskManager.vala"
	_tmp1_ = json_builder_new ();
#line 36 "../src/Services/TaskManager.vala"
	b = _tmp1_;
#line 37 "../src/Services/TaskManager.vala"
	_tmp2_ = b;
#line 37 "../src/Services/TaskManager.vala"
	self->builder = _tmp2_;
#line 39 "../src/Services/TaskManager.vala"
	_tmp3_ = self->builder;
#line 39 "../src/Services/TaskManager.vala"
	json_builder_begin_array (_tmp3_);
#line 40 "../src/Services/TaskManager.vala"
	n = g_list_model_get_n_items ((GListModel*) liststore);
#line 242 "TaskManager.c"
	{
		gboolean _tmp4_ = FALSE;
#line 41 "../src/Services/TaskManager.vala"
		i = (guint) 0;
#line 41 "../src/Services/TaskManager.vala"
		_tmp4_ = TRUE;
#line 41 "../src/Services/TaskManager.vala"
		while (TRUE) {
#line 251 "TaskManager.c"
			JsonBuilder* _tmp6_;
			GObject* item = NULL;
			GObject* _tmp7_;
			JsonBuilder* _tmp8_;
			GObject* _tmp9_;
			const gchar* _tmp10_;
			const gchar* _tmp11_;
			JsonBuilder* _tmp12_;
			GObject* _tmp13_;
			const gchar* _tmp14_;
			const gchar* _tmp15_;
			JsonBuilder* _tmp16_;
#line 41 "../src/Services/TaskManager.vala"
			if (!_tmp4_) {
#line 266 "TaskManager.c"
				guint _tmp5_;
#line 41 "../src/Services/TaskManager.vala"
				_tmp5_ = i;
#line 41 "../src/Services/TaskManager.vala"
				i = _tmp5_ + 1;
#line 272 "TaskManager.c"
			}
#line 41 "../src/Services/TaskManager.vala"
			_tmp4_ = FALSE;
#line 41 "../src/Services/TaskManager.vala"
			if (!(i < n)) {
#line 41 "../src/Services/TaskManager.vala"
				break;
#line 280 "TaskManager.c"
			}
#line 42 "../src/Services/TaskManager.vala"
			_tmp6_ = self->builder;
#line 42 "../src/Services/TaskManager.vala"
			json_builder_begin_array (_tmp6_);
#line 43 "../src/Services/TaskManager.vala"
			_tmp7_ = g_list_model_get_item ((GListModel*) liststore, i);
#line 43 "../src/Services/TaskManager.vala"
			item = _tmp7_;
#line 44 "../src/Services/TaskManager.vala"
			_tmp8_ = self->builder;
#line 44 "../src/Services/TaskManager.vala"
			_tmp9_ = item;
#line 44 "../src/Services/TaskManager.vala"
			_tmp10_ = khronos_log_get_name (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, KHRONOS_TYPE_LOG, KhronosLog));
#line 44 "../src/Services/TaskManager.vala"
			_tmp11_ = _tmp10_;
#line 44 "../src/Services/TaskManager.vala"
			json_builder_add_string_value (_tmp8_, _tmp11_);
#line 45 "../src/Services/TaskManager.vala"
			_tmp12_ = self->builder;
#line 45 "../src/Services/TaskManager.vala"
			_tmp13_ = item;
#line 45 "../src/Services/TaskManager.vala"
			_tmp14_ = khronos_log_get_timedate (G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, KHRONOS_TYPE_LOG, KhronosLog));
#line 45 "../src/Services/TaskManager.vala"
			_tmp15_ = _tmp14_;
#line 45 "../src/Services/TaskManager.vala"
			json_builder_add_string_value (_tmp12_, _tmp15_);
#line 46 "../src/Services/TaskManager.vala"
			_tmp16_ = self->builder;
#line 46 "../src/Services/TaskManager.vala"
			json_builder_end_array (_tmp16_);
#line 41 "../src/Services/TaskManager.vala"
			_g_object_unref0 (item);
#line 316 "TaskManager.c"
		}
	}
#line 48 "../src/Services/TaskManager.vala"
	_tmp17_ = self->builder;
#line 48 "../src/Services/TaskManager.vala"
	json_builder_end_array (_tmp17_);
#line 50 "../src/Services/TaskManager.vala"
	_tmp18_ = json_generator_new ();
#line 50 "../src/Services/TaskManager.vala"
	generator = _tmp18_;
#line 51 "../src/Services/TaskManager.vala"
	_tmp19_ = self->builder;
#line 51 "../src/Services/TaskManager.vala"
	_tmp20_ = json_builder_get_root (_tmp19_);
#line 51 "../src/Services/TaskManager.vala"
	root = _tmp20_;
#line 52 "../src/Services/TaskManager.vala"
	_tmp21_ = generator;
#line 52 "../src/Services/TaskManager.vala"
	_tmp22_ = root;
#line 52 "../src/Services/TaskManager.vala"
	json_generator_set_root (_tmp21_, _tmp22_);
#line 53 "../src/Services/TaskManager.vala"
	_tmp23_ = generator;
#line 53 "../src/Services/TaskManager.vala"
	_tmp24_ = json_generator_to_data (_tmp23_, NULL);
#line 53 "../src/Services/TaskManager.vala"
	_g_free0 (json_string);
#line 53 "../src/Services/TaskManager.vala"
	json_string = _tmp24_;
#line 55 "../src/Services/TaskManager.vala"
	_tmp25_ = self->priv->app_dir;
#line 55 "../src/Services/TaskManager.vala"
	_tmp26_ = g_file_new_for_path (_tmp25_);
#line 55 "../src/Services/TaskManager.vala"
	dir = _tmp26_;
#line 56 "../src/Services/TaskManager.vala"
	_tmp27_ = self->priv->file_name;
#line 56 "../src/Services/TaskManager.vala"
	_tmp28_ = g_file_new_for_path (_tmp27_);
#line 56 "../src/Services/TaskManager.vala"
	file = _tmp28_;
#line 359 "TaskManager.c"
	{
		GFile* _tmp29_;
		GFile* _tmp31_;
		GFile* _tmp33_;
		gchar* _tmp34_;
		gchar* _tmp35_;
		const gchar* _tmp36_;
#line 58 "../src/Services/TaskManager.vala"
		_tmp29_ = dir;
#line 58 "../src/Services/TaskManager.vala"
		if (!g_file_query_exists (_tmp29_, NULL)) {
#line 371 "TaskManager.c"
			GFile* _tmp30_;
#line 59 "../src/Services/TaskManager.vala"
			_tmp30_ = dir;
#line 59 "../src/Services/TaskManager.vala"
			g_file_make_directory (_tmp30_, NULL, &_inner_error0_);
#line 59 "../src/Services/TaskManager.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 379 "TaskManager.c"
				goto __catch0_g_error;
			}
		}
#line 61 "../src/Services/TaskManager.vala"
		_tmp31_ = file;
#line 61 "../src/Services/TaskManager.vala"
		if (g_file_query_exists (_tmp31_, NULL)) {
#line 387 "TaskManager.c"
			GFile* _tmp32_;
#line 62 "../src/Services/TaskManager.vala"
			_tmp32_ = file;
#line 62 "../src/Services/TaskManager.vala"
			g_file_delete (_tmp32_, NULL, &_inner_error0_);
#line 62 "../src/Services/TaskManager.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 395 "TaskManager.c"
				goto __catch0_g_error;
			}
		}
#line 64 "../src/Services/TaskManager.vala"
		_tmp33_ = file;
#line 64 "../src/Services/TaskManager.vala"
		_tmp34_ = g_file_get_path (_tmp33_);
#line 64 "../src/Services/TaskManager.vala"
		_tmp35_ = _tmp34_;
#line 64 "../src/Services/TaskManager.vala"
		_tmp36_ = json_string;
#line 64 "../src/Services/TaskManager.vala"
		g_file_set_contents (_tmp35_, _tmp36_, (gssize) -1, &_inner_error0_);
#line 64 "../src/Services/TaskManager.vala"
		_g_free0 (_tmp35_);
#line 64 "../src/Services/TaskManager.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 413 "TaskManager.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp37_;
		const gchar* _tmp38_;
#line 57 "../src/Services/TaskManager.vala"
		e = _inner_error0_;
#line 57 "../src/Services/TaskManager.vala"
		_inner_error0_ = NULL;
#line 66 "../src/Services/TaskManager.vala"
		_tmp37_ = e;
#line 66 "../src/Services/TaskManager.vala"
		_tmp38_ = _tmp37_->message;
#line 66 "../src/Services/TaskManager.vala"
		g_warning ("TaskManager.vala:66: Failed to save file: %s\n", _tmp38_);
#line 57 "../src/Services/TaskManager.vala"
		_g_error_free0 (e);
#line 435 "TaskManager.c"
	}
	__finally0:
#line 57 "../src/Services/TaskManager.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 57 "../src/Services/TaskManager.vala"
		_g_object_unref0 (file);
#line 57 "../src/Services/TaskManager.vala"
		_g_object_unref0 (dir);
#line 57 "../src/Services/TaskManager.vala"
		__vala_JsonNode_free0 (root);
#line 57 "../src/Services/TaskManager.vala"
		_g_object_unref0 (generator);
#line 57 "../src/Services/TaskManager.vala"
		_g_object_unref0 (b);
#line 57 "../src/Services/TaskManager.vala"
		_g_free0 (json_string);
#line 57 "../src/Services/TaskManager.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 57 "../src/Services/TaskManager.vala"
		g_clear_error (&_inner_error0_);
#line 57 "../src/Services/TaskManager.vala"
		return;
#line 458 "TaskManager.c"
	}
#line 34 "../src/Services/TaskManager.vala"
	_g_object_unref0 (file);
#line 34 "../src/Services/TaskManager.vala"
	_g_object_unref0 (dir);
#line 34 "../src/Services/TaskManager.vala"
	__vala_JsonNode_free0 (root);
#line 34 "../src/Services/TaskManager.vala"
	_g_object_unref0 (generator);
#line 34 "../src/Services/TaskManager.vala"
	_g_object_unref0 (b);
#line 34 "../src/Services/TaskManager.vala"
	_g_free0 (json_string);
#line 472 "TaskManager.c"
}

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
#line 79 "../src/Services/TaskManager.vala"
	return g_boxed_copy (json_node_get_type (), self);
#line 480 "TaskManager.c"
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
#line 79 "../src/Services/TaskManager.vala"
	return self ? _vala_JsonNode_copy (self) : NULL;
#line 488 "TaskManager.c"
}

static gpointer
_json_array_ref0 (gpointer self)
{
#line 80 "../src/Services/TaskManager.vala"
	return self ? json_array_ref (self) : NULL;
#line 496 "TaskManager.c"
}

void
khronos_task_manager_load_from_file (KhronosTaskManager* self)
{
	GError* _inner_error0_ = NULL;
#line 71 "../src/Services/TaskManager.vala"
	g_return_if_fail (self != NULL);
#line 505 "TaskManager.c"
	{
		GFile* file = NULL;
		const gchar* _tmp0_;
		GFile* _tmp1_;
		gchar* json_string = NULL;
		gchar* _tmp2_;
		GFile* _tmp3_;
#line 73 "../src/Services/TaskManager.vala"
		_tmp0_ = self->priv->file_name;
#line 73 "../src/Services/TaskManager.vala"
		_tmp1_ = g_file_new_for_path (_tmp0_);
#line 73 "../src/Services/TaskManager.vala"
		file = _tmp1_;
#line 74 "../src/Services/TaskManager.vala"
		_tmp2_ = g_strdup ("");
#line 74 "../src/Services/TaskManager.vala"
		json_string = _tmp2_;
#line 75 "../src/Services/TaskManager.vala"
		_tmp3_ = file;
#line 75 "../src/Services/TaskManager.vala"
		if (g_file_query_exists (_tmp3_, NULL)) {
#line 527 "TaskManager.c"
			GFile* _tmp4_;
			gchar* _tmp5_;
			gchar* _tmp6_;
			gchar* _tmp7_ = NULL;
			JsonParser* parser = NULL;
			JsonParser* _tmp8_;
			JsonParser* _tmp9_;
			const gchar* _tmp10_;
			JsonNode* root = NULL;
			JsonParser* _tmp11_;
			JsonNode* _tmp12_;
			JsonNode* _tmp13_;
			JsonArray* array = NULL;
			JsonNode* _tmp14_;
			JsonArray* _tmp15_;
			JsonArray* _tmp16_;
			JsonArray* _tmp17_;
			GList* _tmp18_;
#line 76 "../src/Services/TaskManager.vala"
			_tmp4_ = file;
#line 76 "../src/Services/TaskManager.vala"
			_tmp5_ = g_file_get_path (_tmp4_);
#line 76 "../src/Services/TaskManager.vala"
			_tmp6_ = _tmp5_;
#line 76 "../src/Services/TaskManager.vala"
			g_file_get_contents (_tmp6_, &_tmp7_, NULL, &_inner_error0_);
#line 76 "../src/Services/TaskManager.vala"
			_g_free0 (json_string);
#line 76 "../src/Services/TaskManager.vala"
			json_string = _tmp7_;
#line 76 "../src/Services/TaskManager.vala"
			_g_free0 (_tmp6_);
#line 76 "../src/Services/TaskManager.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 76 "../src/Services/TaskManager.vala"
				_g_free0 (json_string);
#line 76 "../src/Services/TaskManager.vala"
				_g_object_unref0 (file);
#line 566 "TaskManager.c"
				goto __catch0_g_error;
			}
#line 77 "../src/Services/TaskManager.vala"
			_tmp8_ = json_parser_new ();
#line 77 "../src/Services/TaskManager.vala"
			parser = _tmp8_;
#line 78 "../src/Services/TaskManager.vala"
			_tmp9_ = parser;
#line 78 "../src/Services/TaskManager.vala"
			_tmp10_ = json_string;
#line 78 "../src/Services/TaskManager.vala"
			json_parser_load_from_data (_tmp9_, _tmp10_, (gssize) -1, &_inner_error0_);
#line 78 "../src/Services/TaskManager.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 78 "../src/Services/TaskManager.vala"
				_g_object_unref0 (parser);
#line 78 "../src/Services/TaskManager.vala"
				_g_free0 (json_string);
#line 78 "../src/Services/TaskManager.vala"
				_g_object_unref0 (file);
#line 587 "TaskManager.c"
				goto __catch0_g_error;
			}
#line 79 "../src/Services/TaskManager.vala"
			_tmp11_ = parser;
#line 79 "../src/Services/TaskManager.vala"
			_tmp12_ = json_parser_get_root (_tmp11_);
#line 79 "../src/Services/TaskManager.vala"
			_tmp13_ = __vala_JsonNode_copy0 (_tmp12_);
#line 79 "../src/Services/TaskManager.vala"
			root = _tmp13_;
#line 80 "../src/Services/TaskManager.vala"
			_tmp14_ = root;
#line 80 "../src/Services/TaskManager.vala"
			_tmp15_ = json_node_get_array (_tmp14_);
#line 80 "../src/Services/TaskManager.vala"
			_tmp16_ = _json_array_ref0 (_tmp15_);
#line 80 "../src/Services/TaskManager.vala"
			array = _tmp16_;
#line 81 "../src/Services/TaskManager.vala"
			_tmp17_ = array;
#line 81 "../src/Services/TaskManager.vala"
			_tmp18_ = json_array_get_elements (_tmp17_);
#line 610 "TaskManager.c"
			{
				GList* tasks_collection = NULL;
				GList* tasks_it = NULL;
#line 81 "../src/Services/TaskManager.vala"
				tasks_collection = _tmp18_;
#line 81 "../src/Services/TaskManager.vala"
				for (tasks_it = tasks_collection; tasks_it != NULL; tasks_it = tasks_it->next) {
#line 618 "TaskManager.c"
					JsonNode* tasks = NULL;
#line 81 "../src/Services/TaskManager.vala"
					tasks = (JsonNode*) tasks_it->data;
#line 622 "TaskManager.c"
					{
						JsonArray* task = NULL;
						JsonNode* _tmp19_;
						JsonArray* _tmp20_;
						JsonArray* _tmp21_;
						gchar* name = NULL;
						JsonArray* _tmp22_;
						const gchar* _tmp23_;
						gchar* _tmp24_;
						gchar* timedate = NULL;
						JsonArray* _tmp25_;
						const gchar* _tmp26_;
						gchar* _tmp27_;
						KhronosMainWindow* _tmp28_;
						const gchar* _tmp29_;
						const gchar* _tmp30_;
#line 82 "../src/Services/TaskManager.vala"
						_tmp19_ = tasks;
#line 82 "../src/Services/TaskManager.vala"
						_tmp20_ = json_node_get_array (_tmp19_);
#line 82 "../src/Services/TaskManager.vala"
						_tmp21_ = _json_array_ref0 (_tmp20_);
#line 82 "../src/Services/TaskManager.vala"
						task = _tmp21_;
#line 83 "../src/Services/TaskManager.vala"
						_tmp22_ = task;
#line 83 "../src/Services/TaskManager.vala"
						_tmp23_ = json_array_get_string_element (_tmp22_, (guint) 0);
#line 83 "../src/Services/TaskManager.vala"
						_tmp24_ = g_strdup (_tmp23_);
#line 83 "../src/Services/TaskManager.vala"
						name = _tmp24_;
#line 84 "../src/Services/TaskManager.vala"
						_tmp25_ = task;
#line 84 "../src/Services/TaskManager.vala"
						_tmp26_ = json_array_get_string_element (_tmp25_, (guint) 1);
#line 84 "../src/Services/TaskManager.vala"
						_tmp27_ = g_strdup (_tmp26_);
#line 84 "../src/Services/TaskManager.vala"
						timedate = _tmp27_;
#line 86 "../src/Services/TaskManager.vala"
						_tmp28_ = self->win;
#line 86 "../src/Services/TaskManager.vala"
						_tmp29_ = name;
#line 86 "../src/Services/TaskManager.vala"
						_tmp30_ = timedate;
#line 86 "../src/Services/TaskManager.vala"
						khronos_main_window_add_task (_tmp28_, _tmp29_, _tmp30_);
#line 81 "../src/Services/TaskManager.vala"
						_g_free0 (timedate);
#line 81 "../src/Services/TaskManager.vala"
						_g_free0 (name);
#line 81 "../src/Services/TaskManager.vala"
						_json_array_unref0 (task);
#line 677 "TaskManager.c"
					}
				}
#line 81 "../src/Services/TaskManager.vala"
				(tasks_collection == NULL) ? NULL : (tasks_collection = (g_list_free (tasks_collection), NULL));
#line 682 "TaskManager.c"
			}
#line 75 "../src/Services/TaskManager.vala"
			_json_array_unref0 (array);
#line 75 "../src/Services/TaskManager.vala"
			__vala_JsonNode_free0 (root);
#line 75 "../src/Services/TaskManager.vala"
			_g_object_unref0 (parser);
#line 690 "TaskManager.c"
		}
#line 72 "../src/Services/TaskManager.vala"
		_g_free0 (json_string);
#line 72 "../src/Services/TaskManager.vala"
		_g_object_unref0 (file);
#line 696 "TaskManager.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp31_;
		const gchar* _tmp32_;
#line 72 "../src/Services/TaskManager.vala"
		e = _inner_error0_;
#line 72 "../src/Services/TaskManager.vala"
		_inner_error0_ = NULL;
#line 90 "../src/Services/TaskManager.vala"
		_tmp31_ = e;
#line 90 "../src/Services/TaskManager.vala"
		_tmp32_ = _tmp31_->message;
#line 90 "../src/Services/TaskManager.vala"
		g_warning ("TaskManager.vala:90: Failed to load file: %s\n", _tmp32_);
#line 72 "../src/Services/TaskManager.vala"
		_g_error_free0 (e);
#line 716 "TaskManager.c"
	}
	__finally0:
#line 72 "../src/Services/TaskManager.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 72 "../src/Services/TaskManager.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 72 "../src/Services/TaskManager.vala"
		g_clear_error (&_inner_error0_);
#line 72 "../src/Services/TaskManager.vala"
		return;
#line 727 "TaskManager.c"
	}
}

static void
khronos_value_task_manager_init (GValue* value)
{
#line 21 "../src/Services/TaskManager.vala"
	value->data[0].v_pointer = NULL;
#line 736 "TaskManager.c"
}

static void
khronos_value_task_manager_free_value (GValue* value)
{
#line 21 "../src/Services/TaskManager.vala"
	if (value->data[0].v_pointer) {
#line 21 "../src/Services/TaskManager.vala"
		khronos_task_manager_unref (value->data[0].v_pointer);
#line 746 "TaskManager.c"
	}
}

static void
khronos_value_task_manager_copy_value (const GValue* src_value,
                                       GValue* dest_value)
{
#line 21 "../src/Services/TaskManager.vala"
	if (src_value->data[0].v_pointer) {
#line 21 "../src/Services/TaskManager.vala"
		dest_value->data[0].v_pointer = khronos_task_manager_ref (src_value->data[0].v_pointer);
#line 758 "TaskManager.c"
	} else {
#line 21 "../src/Services/TaskManager.vala"
		dest_value->data[0].v_pointer = NULL;
#line 762 "TaskManager.c"
	}
}

static gpointer
khronos_value_task_manager_peek_pointer (const GValue* value)
{
#line 21 "../src/Services/TaskManager.vala"
	return value->data[0].v_pointer;
#line 771 "TaskManager.c"
}

static gchar*
khronos_value_task_manager_collect_value (GValue* value,
                                          guint n_collect_values,
                                          GTypeCValue* collect_values,
                                          guint collect_flags)
{
#line 21 "../src/Services/TaskManager.vala"
	if (collect_values[0].v_pointer) {
#line 782 "TaskManager.c"
		KhronosTaskManager * object;
		object = collect_values[0].v_pointer;
#line 21 "../src/Services/TaskManager.vala"
		if (object->parent_instance.g_class == NULL) {
#line 21 "../src/Services/TaskManager.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 789 "TaskManager.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 21 "../src/Services/TaskManager.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 793 "TaskManager.c"
		}
#line 21 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = khronos_task_manager_ref (object);
#line 797 "TaskManager.c"
	} else {
#line 21 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = NULL;
#line 801 "TaskManager.c"
	}
#line 21 "../src/Services/TaskManager.vala"
	return NULL;
#line 805 "TaskManager.c"
}

static gchar*
khronos_value_task_manager_lcopy_value (const GValue* value,
                                        guint n_collect_values,
                                        GTypeCValue* collect_values,
                                        guint collect_flags)
{
	KhronosTaskManager ** object_p;
	object_p = collect_values[0].v_pointer;
#line 21 "../src/Services/TaskManager.vala"
	if (!object_p) {
#line 21 "../src/Services/TaskManager.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 820 "TaskManager.c"
	}
#line 21 "../src/Services/TaskManager.vala"
	if (!value->data[0].v_pointer) {
#line 21 "../src/Services/TaskManager.vala"
		*object_p = NULL;
#line 826 "TaskManager.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 21 "../src/Services/TaskManager.vala"
		*object_p = value->data[0].v_pointer;
#line 830 "TaskManager.c"
	} else {
#line 21 "../src/Services/TaskManager.vala"
		*object_p = khronos_task_manager_ref (value->data[0].v_pointer);
#line 834 "TaskManager.c"
	}
#line 21 "../src/Services/TaskManager.vala"
	return NULL;
#line 838 "TaskManager.c"
}

GParamSpec*
khronos_param_spec_task_manager (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags)
{
	KhronosParamSpecTaskManager* spec;
#line 21 "../src/Services/TaskManager.vala"
	g_return_val_if_fail (g_type_is_a (object_type, KHRONOS_TYPE_TASK_MANAGER), NULL);
#line 21 "../src/Services/TaskManager.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 21 "../src/Services/TaskManager.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 21 "../src/Services/TaskManager.vala"
	return G_PARAM_SPEC (spec);
#line 857 "TaskManager.c"
}

gpointer
khronos_value_get_task_manager (const GValue* value)
{
#line 21 "../src/Services/TaskManager.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KHRONOS_TYPE_TASK_MANAGER), NULL);
#line 21 "../src/Services/TaskManager.vala"
	return value->data[0].v_pointer;
#line 867 "TaskManager.c"
}

void
khronos_value_set_task_manager (GValue* value,
                                gpointer v_object)
{
	KhronosTaskManager * old;
#line 21 "../src/Services/TaskManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KHRONOS_TYPE_TASK_MANAGER));
#line 21 "../src/Services/TaskManager.vala"
	old = value->data[0].v_pointer;
#line 21 "../src/Services/TaskManager.vala"
	if (v_object) {
#line 21 "../src/Services/TaskManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KHRONOS_TYPE_TASK_MANAGER));
#line 21 "../src/Services/TaskManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = v_object;
#line 21 "../src/Services/TaskManager.vala"
		khronos_task_manager_ref (value->data[0].v_pointer);
#line 889 "TaskManager.c"
	} else {
#line 21 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = NULL;
#line 893 "TaskManager.c"
	}
#line 21 "../src/Services/TaskManager.vala"
	if (old) {
#line 21 "../src/Services/TaskManager.vala"
		khronos_task_manager_unref (old);
#line 899 "TaskManager.c"
	}
}

void
khronos_value_take_task_manager (GValue* value,
                                 gpointer v_object)
{
	KhronosTaskManager * old;
#line 21 "../src/Services/TaskManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KHRONOS_TYPE_TASK_MANAGER));
#line 21 "../src/Services/TaskManager.vala"
	old = value->data[0].v_pointer;
#line 21 "../src/Services/TaskManager.vala"
	if (v_object) {
#line 21 "../src/Services/TaskManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KHRONOS_TYPE_TASK_MANAGER));
#line 21 "../src/Services/TaskManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = v_object;
#line 920 "TaskManager.c"
	} else {
#line 21 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = NULL;
#line 924 "TaskManager.c"
	}
#line 21 "../src/Services/TaskManager.vala"
	if (old) {
#line 21 "../src/Services/TaskManager.vala"
		khronos_task_manager_unref (old);
#line 930 "TaskManager.c"
	}
}

static void
khronos_task_manager_class_init (KhronosTaskManagerClass * klass,
                                 gpointer klass_data)
{
#line 21 "../src/Services/TaskManager.vala"
	khronos_task_manager_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/Services/TaskManager.vala"
	((KhronosTaskManagerClass *) klass)->finalize = khronos_task_manager_finalize;
#line 21 "../src/Services/TaskManager.vala"
	g_type_class_adjust_private_offset (klass, &KhronosTaskManager_private_offset);
#line 944 "TaskManager.c"
}

static void
khronos_task_manager_instance_init (KhronosTaskManager * self,
                                    gpointer klass)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 21 "../src/Services/TaskManager.vala"
	self->priv = khronos_task_manager_get_instance_private (self);
#line 22 "../src/Services/TaskManager.vala"
	self->win = NULL;
#line 24 "../src/Services/TaskManager.vala"
	_tmp0_ = g_get_user_data_dir ();
#line 24 "../src/Services/TaskManager.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/io.github.lainsce.Khronos", NULL);
#line 24 "../src/Services/TaskManager.vala"
	self->priv->app_dir = _tmp1_;
#line 21 "../src/Services/TaskManager.vala"
	self->ref_count = 1;
#line 965 "TaskManager.c"
}

static void
khronos_task_manager_finalize (KhronosTaskManager * obj)
{
	KhronosTaskManager * self;
#line 21 "../src/Services/TaskManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KHRONOS_TYPE_TASK_MANAGER, KhronosTaskManager);
#line 21 "../src/Services/TaskManager.vala"
	g_signal_handlers_destroy (self);
#line 24 "../src/Services/TaskManager.vala"
	_g_free0 (self->priv->app_dir);
#line 26 "../src/Services/TaskManager.vala"
	_g_free0 (self->priv->file_name);
#line 980 "TaskManager.c"
}

static GType
khronos_task_manager_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { khronos_value_task_manager_init, khronos_value_task_manager_free_value, khronos_value_task_manager_copy_value, khronos_value_task_manager_peek_pointer, "p", khronos_value_task_manager_collect_value, "p", khronos_value_task_manager_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (KhronosTaskManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) khronos_task_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KhronosTaskManager), 0, (GInstanceInitFunc) khronos_task_manager_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType khronos_task_manager_type_id;
	khronos_task_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "KhronosTaskManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
	KhronosTaskManager_private_offset = g_type_add_instance_private (khronos_task_manager_type_id, sizeof (KhronosTaskManagerPrivate));
	return khronos_task_manager_type_id;
}

GType
khronos_task_manager_get_type (void)
{
	static volatile gsize khronos_task_manager_type_id__volatile = 0;
	if (g_once_init_enter (&khronos_task_manager_type_id__volatile)) {
		GType khronos_task_manager_type_id;
		khronos_task_manager_type_id = khronos_task_manager_get_type_once ();
		g_once_init_leave (&khronos_task_manager_type_id__volatile, khronos_task_manager_type_id);
	}
	return khronos_task_manager_type_id__volatile;
}

gpointer
khronos_task_manager_ref (gpointer instance)
{
	KhronosTaskManager * self;
	self = instance;
#line 21 "../src/Services/TaskManager.vala"
	g_atomic_int_inc (&self->ref_count);
#line 21 "../src/Services/TaskManager.vala"
	return instance;
#line 1016 "TaskManager.c"
}

void
khronos_task_manager_unref (gpointer instance)
{
	KhronosTaskManager * self;
	self = instance;
#line 21 "../src/Services/TaskManager.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 21 "../src/Services/TaskManager.vala"
		KHRONOS_TASK_MANAGER_GET_CLASS (self)->finalize (self);
#line 21 "../src/Services/TaskManager.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1030 "TaskManager.c"
	}
}

