/* MainWindow.c generated by valac 0.50.2, the Vala compiler
 * generated from MainWindow.vala, do not modify */

/*
* Copyright (c) 2020-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gdk/gdk.h>
#include "config.h"
#include <math.h>
#include <glib/gi18n-lib.h>
#include <float.h>

#define KHRONOS_TYPE_MAIN_WINDOW (khronos_main_window_get_type ())
#define KHRONOS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindow))
#define KHRONOS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindowClass))
#define KHRONOS_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_MAIN_WINDOW))
#define KHRONOS_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_MAIN_WINDOW))
#define KHRONOS_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindowClass))

typedef struct _KhronosMainWindow KhronosMainWindow;
typedef struct _KhronosMainWindowClass KhronosMainWindowClass;
typedef struct _KhronosMainWindowPrivate KhronosMainWindowPrivate;

#define KHRONOS_TYPE_TASK_MANAGER (khronos_task_manager_get_type ())
#define KHRONOS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_TASK_MANAGER, KhronosTaskManager))
#define KHRONOS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_TASK_MANAGER, KhronosTaskManagerClass))
#define KHRONOS_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_TASK_MANAGER))
#define KHRONOS_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_TASK_MANAGER))
#define KHRONOS_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_TASK_MANAGER, KhronosTaskManagerClass))

typedef struct _KhronosTaskManager KhronosTaskManager;
typedef struct _KhronosTaskManagerClass KhronosTaskManagerClass;
enum  {
	KHRONOS_MAIN_WINDOW_0_PROPERTY,
	KHRONOS_MAIN_WINDOW_IS_MODIFIED_PROPERTY,
	KHRONOS_MAIN_WINDOW_APP_PROPERTY,
	KHRONOS_MAIN_WINDOW_ACTIONS_PROPERTY,
	KHRONOS_MAIN_WINDOW_NUM_PROPERTIES
};
static GParamSpec* khronos_main_window_properties[KHRONOS_MAIN_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _khronos_task_manager_unref0(var) ((var == NULL) ? NULL : (var = (khronos_task_manager_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define KHRONOS_TYPE_LOG_ROW (khronos_log_row_get_type ())
#define KHRONOS_LOG_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_LOG_ROW, KhronosLogRow))
#define KHRONOS_LOG_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_LOG_ROW, KhronosLogRowClass))
#define KHRONOS_IS_LOG_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_LOG_ROW))
#define KHRONOS_IS_LOG_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_LOG_ROW))
#define KHRONOS_LOG_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_LOG_ROW, KhronosLogRowClass))

typedef struct _KhronosLogRow KhronosLogRow;
typedef struct _KhronosLogRowClass KhronosLogRowClass;

#define KHRONOS_TYPE_LOG (khronos_log_get_type ())
#define KHRONOS_LOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_LOG, KhronosLog))
#define KHRONOS_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_LOG, KhronosLogClass))
#define KHRONOS_IS_LOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_LOG))
#define KHRONOS_IS_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_LOG))
#define KHRONOS_LOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_LOG, KhronosLogClass))

typedef struct _KhronosLog KhronosLog;
typedef struct _KhronosLogClass KhronosLogClass;

#define KHRONOS_TYPE_PREFS (khronos_prefs_get_type ())
#define KHRONOS_PREFS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_PREFS, KhronosPrefs))
#define KHRONOS_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_PREFS, KhronosPrefsClass))
#define KHRONOS_IS_PREFS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_PREFS))
#define KHRONOS_IS_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_PREFS))
#define KHRONOS_PREFS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_PREFS, KhronosPrefsClass))

typedef struct _KhronosPrefs KhronosPrefs;
typedef struct _KhronosPrefsClass KhronosPrefsClass;
typedef struct _KhronosPrefsPrivate KhronosPrefsPrivate;
typedef void (*KhronosMainWindowHookFunc) (gpointer user_data);
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _KhronosMainWindow {
	AdwApplicationWindow parent_instance;
	KhronosMainWindowPrivate * priv;
	GtkListBox* column;
	GtkEntry* column_entry;
	GtkLabel* column_time_label;
	GtkButton* column_button;
	GtkButton* column_play_button;
	GtkMenuButton* menu_button;
	GtkButton* trash_button;
	GtkMenuButton* menu_button2;
	AdwViewSwitcher* win_switcher;
	AdwViewSwitcher* win_switcher2;
	GtkStack* title_stack;
	GtkStack* win_stack;
	GtkBox* placeholder;
	gboolean start;
	KhronosTaskManager* tm;
};

struct _KhronosMainWindowClass {
	AdwApplicationWindowClass parent_class;
};

struct _KhronosMainWindowPrivate {
	GListStore* liststore;
	gboolean _is_modified;
	guint timer_id;
	guint sec;
	guint min;
	guint hrs;
	GtkApplication* _app;
	guint id1;
	guint id2;
	guint id3;
	guint id4;
	guint id5;
	GSimpleActionGroup* _actions;
};

struct _KhronosPrefs {
	AdwPreferencesWindow parent_instance;
	KhronosPrefsPrivate * priv;
	GtkSwitch* darkmode;
};

struct _KhronosPrefsClass {
	AdwPreferencesWindowClass parent_class;
};

static gint KhronosMainWindow_private_offset;
static gpointer khronos_main_window_parent_class = NULL;
extern GeeMultiMap* khronos_main_window_action_accelerators;
GeeMultiMap* khronos_main_window_action_accelerators = NULL;
extern GSettings* khronos_application_gsettings;

GType khronos_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosMainWindow, g_object_unref)
gpointer khronos_task_manager_ref (gpointer instance);
void khronos_task_manager_unref (gpointer instance);
GParamSpec* khronos_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void khronos_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void khronos_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer khronos_value_get_task_manager (const GValue* value);
GType khronos_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosTaskManager, khronos_task_manager_unref)
#define KHRONOS_MAIN_WINDOW_ACTION_PREFIX "win."
#define KHRONOS_MAIN_WINDOW_ACTION_PREFS "prefs"
#define KHRONOS_MAIN_WINDOW_ACTION_ABOUT "about"
#define KHRONOS_MAIN_WINDOW_ACTION_EXPORT "export"
#define KHRONOS_MAIN_WINDOW_ACTION_DELETE_ROW "delete_row"
void khronos_main_window_action_prefs (KhronosMainWindow* self);
static void _khronos_main_window_action_prefs_gsimple_action_activate_callback (GSimpleAction* action,
                                                                         GVariant* parameter,
                                                                         gpointer self);
void khronos_main_window_action_export (KhronosMainWindow* self);
static void _khronos_main_window_action_export_gsimple_action_activate_callback (GSimpleAction* action,
                                                                          GVariant* parameter,
                                                                          gpointer self);
void khronos_main_window_action_delete_row (KhronosMainWindow* self);
static void _khronos_main_window_action_delete_row_gsimple_action_activate_callback (GSimpleAction* action,
                                                                              GVariant* parameter,
                                                                              gpointer self);
void khronos_main_window_action_about (KhronosMainWindow* self);
static void _khronos_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                         GVariant* parameter,
                                                                         gpointer self);
KhronosMainWindow* khronos_main_window_new (GtkApplication* application);
KhronosMainWindow* khronos_main_window_construct (GType object_type,
                                                  GtkApplication* application);
void khronos_main_window_set_actions (KhronosMainWindow* self,
                                      GSimpleActionGroup* value);
GSimpleActionGroup* khronos_main_window_get_actions (KhronosMainWindow* self);
static void _vala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
GtkApplication* khronos_main_window_get_app (KhronosMainWindow* self);
static gboolean khronos_main_window_real_close_request (GtkWindow* base);
void khronos_main_window_listen_to_changes (KhronosMainWindow* self);
static GtkWidget* __lambda5_ (KhronosMainWindow* self,
                       GObject* item);
GType khronos_log_row_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosLogRow, g_object_unref)
KhronosLogRow* khronos_main_window_make_widgets (KhronosMainWindow* self,
                                                 GObject* item);
static GtkWidget* ___lambda5__gtk_list_box_create_widget_func (GObject* item,
                                                        gpointer self);
GType khronos_log_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosLog, g_object_unref)
KhronosLogRow* khronos_log_row_new (KhronosLog* log);
KhronosLogRow* khronos_log_row_construct (GType object_type,
                                          KhronosLog* log);
void khronos_main_window_reset_timer (KhronosMainWindow* self);
void khronos_main_window_add_task (KhronosMainWindow* self,
                                   const gchar* name,
                                   const gchar* timedate);
KhronosLog* khronos_log_new (void);
KhronosLog* khronos_log_construct (GType object_type);
void khronos_log_set_name (KhronosLog* self,
                           const gchar* value);
void khronos_log_set_timedate (KhronosLog* self,
                               const gchar* value);
void khronos_main_window_timer (KhronosMainWindow* self);
void khronos_main_window_set_timeouts (KhronosMainWindow* self);
static gboolean ___lambda6_ (KhronosMainWindow* self);
void khronos_main_window_notification1 (KhronosMainWindow* self);
static gboolean ____lambda6__gsource_func (gpointer self);
static gboolean ___lambda7_ (KhronosMainWindow* self);
void khronos_main_window_notification2 (KhronosMainWindow* self);
static gboolean ____lambda7__gsource_func (gpointer self);
static gboolean ___lambda8_ (KhronosMainWindow* self);
void khronos_main_window_notification3 (KhronosMainWindow* self);
static gboolean ____lambda8__gsource_func (gpointer self);
static gboolean ___lambda9_ (KhronosMainWindow* self);
void khronos_main_window_notification4 (KhronosMainWindow* self);
static gboolean ____lambda9__gsource_func (gpointer self);
static gboolean ___lambda10_ (KhronosMainWindow* self);
void khronos_main_window_notification5 (KhronosMainWindow* self);
static gboolean ____lambda10__gsource_func (gpointer self);
void khronos_file_manager_save_as (GListStore* liststore,
                                   GAsyncReadyCallback _callback_,
                                   gpointer _user_data_);
void khronos_file_manager_save_as_finish (GAsyncResult* _res_,
                                          GError** error);
GType khronos_prefs_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosPrefs, g_object_unref)
KhronosPrefs* khronos_prefs_new (void);
KhronosPrefs* khronos_prefs_construct (GType object_type);
void khronos_prefs_set_delay (KhronosPrefs* self,
                              gint value);
gboolean khronos_main_window_get_is_modified (KhronosMainWindow* self);
void khronos_main_window_set_is_modified (KhronosMainWindow* self,
                                          gboolean value);
static void khronos_main_window_set_app (KhronosMainWindow* self,
                                  GtkApplication* value);
static GObject * khronos_main_window_constructor (GType type,
                                           guint n_construct_properties,
                                           GObjectConstructParam * construct_properties);
KhronosTaskManager* khronos_task_manager_new (KhronosMainWindow* win);
KhronosTaskManager* khronos_task_manager_construct (GType object_type,
                                                    KhronosMainWindow* win);
static void _khronos_main_window___lambda11_ (KhronosMainWindow* self);
static void __khronos_main_window___lambda11__g_settings_changed (GSettings* _sender,
                                                           const gchar* key,
                                                           gpointer self);
static void _khronos_main_window___lambda12_ (KhronosMainWindow* self,
                                       GtkListBoxRow* actrow);
KhronosLog* khronos_log_row_get_log (KhronosLogRow* self);
const gchar* khronos_log_get_name (KhronosLog* self);
static void __khronos_main_window___lambda12__gtk_list_box_row_activated (GtkListBox* _sender,
                                                                   GtkListBoxRow* row,
                                                                   gpointer self);
static void _khronos_main_window___lambda13_ (KhronosMainWindow* self);
void khronos_task_manager_save_to_file (KhronosTaskManager* self,
                                        GListStore* liststore);
static void __khronos_main_window___lambda13__gtk_button_clicked (GtkButton* _sender,
                                                           gpointer self);
static void _khronos_main_window___lambda14_ (KhronosMainWindow* self);
static gboolean ___lambda15_ (KhronosMainWindow* self);
static gboolean ____lambda15__gsource_func (gpointer self);
static void __khronos_main_window___lambda14__gtk_button_clicked (GtkButton* _sender,
                                                           gpointer self);
static void _khronos_main_window___lambda16_ (KhronosMainWindow* self);
static void __khronos_main_window___lambda16__gtk_editable_changed (GtkEditable* _sender,
                                                             gpointer self);
static void _khronos_main_window___lambda17_ (KhronosMainWindow* self);
static void __khronos_main_window___lambda17__g_object_notify (GObject* _sender,
                                                        GParamSpec* pspec,
                                                        gpointer self);
static void _khronos_main_window___lambda18_ (KhronosMainWindow* self);
static void __khronos_main_window___lambda18__gtk_button_clicked (GtkButton* _sender,
                                                           gpointer self);
void khronos_task_manager_load_from_file (KhronosTaskManager* self);
static void _khronos_main_window___lambda19_ (KhronosMainWindow* self);
static void __khronos_main_window___lambda19__g_list_model_items_changed (GListModel* _sender,
                                                                   guint position,
                                                                   guint removed,
                                                                   guint added,
                                                                   gpointer self);
static void khronos_main_window_finalize (GObject * obj);
static GType khronos_main_window_get_type_once (void);
static void _vala_khronos_main_window_get_property (GObject * object,
                                             guint property_id,
                                             GValue * value,
                                             GParamSpec * pspec);
static void _vala_khronos_main_window_set_property (GObject * object,
                                             guint property_id,
                                             const GValue * value,
                                             GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static const GActionEntry KHRONOS_MAIN_WINDOW_ACTION_ENTRIES[4] = {{KHRONOS_MAIN_WINDOW_ACTION_PREFS, _khronos_main_window_action_prefs_gsimple_action_activate_callback}, {KHRONOS_MAIN_WINDOW_ACTION_EXPORT, _khronos_main_window_action_export_gsimple_action_activate_callback}, {KHRONOS_MAIN_WINDOW_ACTION_DELETE_ROW, _khronos_main_window_action_delete_row_gsimple_action_activate_callback}, {KHRONOS_MAIN_WINDOW_ACTION_ABOUT, _khronos_main_window_action_about_gsimple_action_activate_callback}};

static inline gpointer
khronos_main_window_get_instance_private (KhronosMainWindow* self)
{
	return G_STRUCT_MEMBER_P (self, KhronosMainWindow_private_offset);
}

static void
_khronos_main_window_action_prefs_gsimple_action_activate_callback (GSimpleAction* action,
                                                                    GVariant* parameter,
                                                                    gpointer self)
{
#line 77 "../src/MainWindow.vala"
	khronos_main_window_action_prefs ((KhronosMainWindow*) self);
#line 341 "MainWindow.c"
}

static void
_khronos_main_window_action_export_gsimple_action_activate_callback (GSimpleAction* action,
                                                                     GVariant* parameter,
                                                                     gpointer self)
{
#line 77 "../src/MainWindow.vala"
	khronos_main_window_action_export ((KhronosMainWindow*) self);
#line 351 "MainWindow.c"
}

static void
_khronos_main_window_action_delete_row_gsimple_action_activate_callback (GSimpleAction* action,
                                                                         GVariant* parameter,
                                                                         gpointer self)
{
#line 77 "../src/MainWindow.vala"
	khronos_main_window_action_delete_row ((KhronosMainWindow*) self);
#line 361 "MainWindow.c"
}

static void
_khronos_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                    GVariant* parameter,
                                                                    gpointer self)
{
#line 77 "../src/MainWindow.vala"
	khronos_main_window_action_about ((KhronosMainWindow*) self);
#line 371 "MainWindow.c"
}

static void
_vala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
#line 104 "../src/MainWindow.vala"
	if ((*length) == (*size)) {
#line 104 "../src/MainWindow.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 104 "../src/MainWindow.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 386 "MainWindow.c"
	}
#line 104 "../src/MainWindow.vala"
	(*array)[(*length)++] = value;
#line 104 "../src/MainWindow.vala"
	(*array)[*length] = NULL;
#line 392 "MainWindow.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 115 "../src/MainWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 400 "MainWindow.c"
}

KhronosMainWindow*
khronos_main_window_construct (GType object_type,
                               GtkApplication* application)
{
	KhronosMainWindow * self = NULL;
	GSettings* _tmp0_;
	GSimpleActionGroup* _tmp3_;
	GSimpleActionGroup* _tmp4_;
	GSimpleActionGroup* _tmp5_;
	GSimpleActionGroup* _tmp6_;
	GtkCssProvider* provider = NULL;
	GtkCssProvider* _tmp27_;
	GtkCssProvider* _tmp28_;
	GdkDisplay* _tmp29_;
	GtkCssProvider* _tmp30_;
	GtkIconTheme* theme = NULL;
	GdkDisplay* _tmp31_;
	GtkIconTheme* _tmp32_;
	GtkIconTheme* _tmp33_;
	GtkIconTheme* _tmp34_;
	GtkStyleContext* style = NULL;
	GtkStyleContext* _tmp35_;
	GtkStyleContext* _tmp36_;
#line 84 "../src/MainWindow.vala"
	g_return_val_if_fail (application != NULL, NULL);
#line 85 "../src/MainWindow.vala"
	self = (KhronosMainWindow*) g_object_new (object_type, "application", application, "app", application, "icon-name", "io.github.lainsce.Khronos", "title", "Khronos", NULL);
#line 92 "../src/MainWindow.vala"
	_tmp0_ = khronos_application_gsettings;
#line 92 "../src/MainWindow.vala"
	if (g_settings_get_boolean (_tmp0_, "dark-mode")) {
#line 434 "MainWindow.c"
		GtkSettings* _tmp1_;
#line 93 "../src/MainWindow.vala"
		_tmp1_ = gtk_settings_get_default ();
#line 93 "../src/MainWindow.vala"
		g_object_set (_tmp1_, "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 440 "MainWindow.c"
	} else {
		GtkSettings* _tmp2_;
#line 95 "../src/MainWindow.vala"
		_tmp2_ = gtk_settings_get_default ();
#line 95 "../src/MainWindow.vala"
		g_object_set (_tmp2_, "gtk-application-prefer-dark-theme", FALSE, NULL);
#line 447 "MainWindow.c"
	}
#line 98 "../src/MainWindow.vala"
	_tmp3_ = g_simple_action_group_new ();
#line 98 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 98 "../src/MainWindow.vala"
	khronos_main_window_set_actions (self, _tmp4_);
#line 98 "../src/MainWindow.vala"
	_g_object_unref0 (_tmp4_);
#line 99 "../src/MainWindow.vala"
	_tmp5_ = self->priv->_actions;
#line 99 "../src/MainWindow.vala"
	g_action_map_add_action_entries ((GActionMap*) _tmp5_, KHRONOS_MAIN_WINDOW_ACTION_ENTRIES, (gint) G_N_ELEMENTS (KHRONOS_MAIN_WINDOW_ACTION_ENTRIES), self);
#line 100 "../src/MainWindow.vala"
	_tmp6_ = self->priv->_actions;
#line 100 "../src/MainWindow.vala"
	gtk_widget_insert_action_group ((GtkWidget*) self, "win", (GActionGroup*) _tmp6_);
#line 465 "MainWindow.c"
	{
		GeeIterator* _action_it = NULL;
		GeeMultiMap* _tmp7_;
		GeeSet* _tmp8_;
		GeeSet* _tmp9_;
		GeeIterator* _tmp10_;
		GeeIterator* _tmp11_;
#line 102 "../src/MainWindow.vala"
		_tmp7_ = khronos_main_window_action_accelerators;
#line 102 "../src/MainWindow.vala"
		_tmp8_ = gee_multi_map_get_keys (_tmp7_);
#line 102 "../src/MainWindow.vala"
		_tmp9_ = _tmp8_;
#line 102 "../src/MainWindow.vala"
		_tmp10_ = gee_iterable_iterator ((GeeIterable*) _tmp9_);
#line 102 "../src/MainWindow.vala"
		_tmp11_ = _tmp10_;
#line 102 "../src/MainWindow.vala"
		_g_object_unref0 (_tmp9_);
#line 102 "../src/MainWindow.vala"
		_action_it = _tmp11_;
#line 102 "../src/MainWindow.vala"
		while (TRUE) {
#line 489 "MainWindow.c"
			GeeIterator* _tmp12_;
			gchar* action = NULL;
			GeeIterator* _tmp13_;
			gpointer _tmp14_;
			gchar** accels_array = NULL;
			GeeMultiMap* _tmp15_;
			const gchar* _tmp16_;
			GeeCollection* _tmp17_;
			GeeCollection* _tmp18_;
			gint _tmp19_ = 0;
			gpointer* _tmp20_;
			gchar** _tmp21_;
			gint _tmp21__length1;
			gint accels_array_length1;
			gint _accels_array_size_;
			GtkApplication* _tmp22_;
			const gchar* _tmp23_;
			gchar* _tmp24_;
			gchar* _tmp25_;
			gchar** _tmp26_;
			gint _tmp26__length1;
#line 102 "../src/MainWindow.vala"
			_tmp12_ = _action_it;
#line 102 "../src/MainWindow.vala"
			if (!gee_iterator_next (_tmp12_)) {
#line 102 "../src/MainWindow.vala"
				break;
#line 517 "MainWindow.c"
			}
#line 102 "../src/MainWindow.vala"
			_tmp13_ = _action_it;
#line 102 "../src/MainWindow.vala"
			_tmp14_ = gee_iterator_get (_tmp13_);
#line 102 "../src/MainWindow.vala"
			action = (gchar*) _tmp14_;
#line 103 "../src/MainWindow.vala"
			_tmp15_ = khronos_main_window_action_accelerators;
#line 103 "../src/MainWindow.vala"
			_tmp16_ = action;
#line 103 "../src/MainWindow.vala"
			_tmp17_ = gee_multi_map_get (_tmp15_, _tmp16_);
#line 103 "../src/MainWindow.vala"
			_tmp18_ = _tmp17_;
#line 103 "../src/MainWindow.vala"
			_tmp20_ = gee_collection_to_array (_tmp18_, &_tmp19_);
#line 103 "../src/MainWindow.vala"
			_tmp21_ = _tmp20_;
#line 103 "../src/MainWindow.vala"
			_tmp21__length1 = _tmp19_;
#line 103 "../src/MainWindow.vala"
			_g_object_unref0 (_tmp18_);
#line 103 "../src/MainWindow.vala"
			accels_array = _tmp21_;
#line 103 "../src/MainWindow.vala"
			accels_array_length1 = _tmp21__length1;
#line 103 "../src/MainWindow.vala"
			_accels_array_size_ = accels_array_length1;
#line 104 "../src/MainWindow.vala"
			_vala_array_add1 (&accels_array, &accels_array_length1, &_accels_array_size_, NULL);
#line 106 "../src/MainWindow.vala"
			_tmp22_ = self->priv->_app;
#line 106 "../src/MainWindow.vala"
			_tmp23_ = action;
#line 106 "../src/MainWindow.vala"
			_tmp24_ = g_strconcat (KHRONOS_MAIN_WINDOW_ACTION_PREFIX, _tmp23_, NULL);
#line 106 "../src/MainWindow.vala"
			_tmp25_ = _tmp24_;
#line 106 "../src/MainWindow.vala"
			_tmp26_ = accels_array;
#line 106 "../src/MainWindow.vala"
			_tmp26__length1 = accels_array_length1;
#line 106 "../src/MainWindow.vala"
			gtk_application_set_accels_for_action (_tmp22_, _tmp25_, _tmp26_);
#line 106 "../src/MainWindow.vala"
			_g_free0 (_tmp25_);
#line 102 "../src/MainWindow.vala"
			accels_array = (_vala_array_free (accels_array, accels_array_length1, (GDestroyNotify) g_free), NULL);
#line 102 "../src/MainWindow.vala"
			_g_free0 (action);
#line 569 "MainWindow.c"
		}
#line 102 "../src/MainWindow.vala"
		_g_object_unref0 (_action_it);
#line 573 "MainWindow.c"
	}
#line 109 "../src/MainWindow.vala"
	_tmp27_ = gtk_css_provider_new ();
#line 109 "../src/MainWindow.vala"
	provider = _tmp27_;
#line 110 "../src/MainWindow.vala"
	_tmp28_ = provider;
#line 110 "../src/MainWindow.vala"
	gtk_css_provider_load_from_resource (_tmp28_, "/io/github/lainsce/Khronos/stylesheet.css");
#line 111 "../src/MainWindow.vala"
	_tmp29_ = gdk_display_get_default ();
#line 111 "../src/MainWindow.vala"
	_tmp30_ = provider;
#line 111 "../src/MainWindow.vala"
	gtk_style_context_add_provider_for_display (_tmp29_, (GtkStyleProvider*) _tmp30_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 115 "../src/MainWindow.vala"
	_tmp31_ = gdk_display_get_default ();
#line 115 "../src/MainWindow.vala"
	_tmp32_ = gtk_icon_theme_get_for_display (_tmp31_);
#line 115 "../src/MainWindow.vala"
	_tmp33_ = _g_object_ref0 (_tmp32_);
#line 115 "../src/MainWindow.vala"
	theme = _tmp33_;
#line 116 "../src/MainWindow.vala"
	_tmp34_ = theme;
#line 116 "../src/MainWindow.vala"
	gtk_icon_theme_add_resource_path (_tmp34_, "/io/github/lainsce/Khronos/");
#line 118 "../src/MainWindow.vala"
	_tmp35_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 118 "../src/MainWindow.vala"
	_tmp36_ = _g_object_ref0 (_tmp35_);
#line 118 "../src/MainWindow.vala"
	style = _tmp36_;
#line 119 "../src/MainWindow.vala"
	if (g_strcmp0 (PROFILE, "Devel") == 0) {
#line 609 "MainWindow.c"
		GtkStyleContext* _tmp37_;
#line 120 "../src/MainWindow.vala"
		_tmp37_ = style;
#line 120 "../src/MainWindow.vala"
		gtk_style_context_add_class (_tmp37_, "devel");
#line 615 "MainWindow.c"
	}
#line 84 "../src/MainWindow.vala"
	_g_object_unref0 (style);
#line 84 "../src/MainWindow.vala"
	_g_object_unref0 (theme);
#line 84 "../src/MainWindow.vala"
	_g_object_unref0 (provider);
#line 84 "../src/MainWindow.vala"
	return self;
#line 625 "MainWindow.c"
}

KhronosMainWindow*
khronos_main_window_new (GtkApplication* application)
{
#line 84 "../src/MainWindow.vala"
	return khronos_main_window_construct (KHRONOS_TYPE_MAIN_WINDOW, application);
#line 633 "MainWindow.c"
}

static gboolean
khronos_main_window_real_close_request (GtkWindow* base)
{
	KhronosMainWindow * self;
	GtkListBox* _tmp0_;
	gboolean result = FALSE;
#line 226 "../src/MainWindow.vala"
	self = (KhronosMainWindow*) base;
#line 227 "../src/MainWindow.vala"
	g_debug ("MainWindow.vala:227: Exiting window... Disposing of stuff...");
#line 228 "../src/MainWindow.vala"
	_tmp0_ = self->column;
#line 228 "../src/MainWindow.vala"
	gtk_list_box_bind_model (_tmp0_, NULL, NULL, NULL, NULL);
#line 229 "../src/MainWindow.vala"
	g_object_run_dispose ((GObject*) self);
#line 230 "../src/MainWindow.vala"
	result = TRUE;
#line 230 "../src/MainWindow.vala"
	return result;
#line 656 "MainWindow.c"
}

static GtkWidget*
__lambda5_ (KhronosMainWindow* self,
            GObject* item)
{
	KhronosLogRow* _tmp0_;
	GtkWidget* result = NULL;
#line 234 "../src/MainWindow.vala"
	g_return_val_if_fail (item != NULL, NULL);
#line 234 "../src/MainWindow.vala"
	_tmp0_ = khronos_main_window_make_widgets (self, item);
#line 234 "../src/MainWindow.vala"
	result = (GtkWidget*) _tmp0_;
#line 234 "../src/MainWindow.vala"
	return result;
#line 673 "MainWindow.c"
}

static GtkWidget*
___lambda5__gtk_list_box_create_widget_func (GObject* item,
                                             gpointer self)
{
	GtkWidget* result;
	result = __lambda5_ ((KhronosMainWindow*) self, item);
#line 234 "../src/MainWindow.vala"
	return result;
#line 684 "MainWindow.c"
}

void
khronos_main_window_listen_to_changes (KhronosMainWindow* self)
{
	GtkListBox* _tmp0_;
	GListStore* _tmp1_;
	GSettings* _tmp2_;
	GSettings* _tmp3_;
#line 233 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 234 "../src/MainWindow.vala"
	_tmp0_ = self->column;
#line 234 "../src/MainWindow.vala"
	_tmp1_ = self->priv->liststore;
#line 234 "../src/MainWindow.vala"
	gtk_list_box_bind_model (_tmp0_, (GListModel*) _tmp1_, ___lambda5__gtk_list_box_create_widget_func, g_object_ref (self), g_object_unref);
#line 235 "../src/MainWindow.vala"
	_tmp2_ = khronos_application_gsettings;
#line 235 "../src/MainWindow.vala"
	g_settings_bind (_tmp2_, "window-width", (GObject*) self, "default-width", G_SETTINGS_BIND_DEFAULT);
#line 236 "../src/MainWindow.vala"
	_tmp3_ = khronos_application_gsettings;
#line 236 "../src/MainWindow.vala"
	g_settings_bind (_tmp3_, "window-height", (GObject*) self, "default-height", G_SETTINGS_BIND_DEFAULT);
#line 710 "MainWindow.c"
}

KhronosLogRow*
khronos_main_window_make_widgets (KhronosMainWindow* self,
                                  GObject* item)
{
	KhronosLogRow* _tmp0_;
	KhronosLogRow* result = NULL;
#line 239 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 239 "../src/MainWindow.vala"
	g_return_val_if_fail (item != NULL, NULL);
#line 240 "../src/MainWindow.vala"
	_tmp0_ = khronos_log_row_new (G_TYPE_CHECK_INSTANCE_CAST (item, KHRONOS_TYPE_LOG, KhronosLog));
#line 240 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp0_);
#line 240 "../src/MainWindow.vala"
	result = _tmp0_;
#line 240 "../src/MainWindow.vala"
	return result;
#line 731 "MainWindow.c"
}

void
khronos_main_window_reset_timer (KhronosMainWindow* self)
{
	GtkLabel* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GtkButton* _tmp3_;
	GtkEntry* _tmp4_;
#line 243 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 244 "../src/MainWindow.vala"
	self->priv->sec = (guint) 0;
#line 245 "../src/MainWindow.vala"
	self->priv->min = (guint) 0;
#line 246 "../src/MainWindow.vala"
	self->priv->hrs = (guint) 0;
#line 247 "../src/MainWindow.vala"
	_tmp0_ = self->column_time_label;
#line 247 "../src/MainWindow.vala"
	_tmp1_ = g_strdup_printf ("<span font_features='tnum'>%02u∶%02u∶%02u</span>", self->priv->hrs, self->priv->min, self->priv->sec);
#line 247 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 247 "../src/MainWindow.vala"
	gtk_label_set_label (_tmp0_, _tmp2_);
#line 247 "../src/MainWindow.vala"
	_g_free0 (_tmp2_);
#line 248 "../src/MainWindow.vala"
	_tmp3_ = self->column_button;
#line 248 "../src/MainWindow.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp3_, FALSE);
#line 249 "../src/MainWindow.vala"
	_tmp4_ = self->column_entry;
#line 249 "../src/MainWindow.vala"
	gtk_editable_set_text ((GtkEditable*) _tmp4_, "");
#line 768 "MainWindow.c"
}

void
khronos_main_window_add_task (KhronosMainWindow* self,
                              const gchar* name,
                              const gchar* timedate)
{
	KhronosLog* log = NULL;
	KhronosLog* _tmp0_;
	GListStore* _tmp1_;
#line 252 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 252 "../src/MainWindow.vala"
	g_return_if_fail (name != NULL);
#line 252 "../src/MainWindow.vala"
	g_return_if_fail (timedate != NULL);
#line 253 "../src/MainWindow.vala"
	_tmp0_ = khronos_log_new ();
#line 253 "../src/MainWindow.vala"
	log = _tmp0_;
#line 254 "../src/MainWindow.vala"
	khronos_log_set_name (log, name);
#line 255 "../src/MainWindow.vala"
	khronos_log_set_timedate (log, timedate);
#line 257 "../src/MainWindow.vala"
	_tmp1_ = self->priv->liststore;
#line 257 "../src/MainWindow.vala"
	g_list_store_append (_tmp1_, (GObject*) log);
#line 252 "../src/MainWindow.vala"
	_g_object_unref0 (log);
#line 799 "MainWindow.c"
}

void
khronos_main_window_timer (KhronosMainWindow* self)
{
#line 260 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 261 "../src/MainWindow.vala"
	if (self->start) {
#line 809 "MainWindow.c"
		GtkLabel* _tmp0_;
		gchar* _tmp1_;
		gchar* _tmp2_;
#line 262 "../src/MainWindow.vala"
		self->priv->sec = self->priv->sec + 1;
#line 263 "../src/MainWindow.vala"
		_tmp0_ = self->column_time_label;
#line 263 "../src/MainWindow.vala"
		_tmp1_ = g_strdup_printf ("<span font_features='tnum'>%02u∶%02u∶%02u</span>", self->priv->hrs, self->priv->min, self->priv->sec);
#line 263 "../src/MainWindow.vala"
		_tmp2_ = _tmp1_;
#line 263 "../src/MainWindow.vala"
		gtk_label_set_label (_tmp0_, _tmp2_);
#line 263 "../src/MainWindow.vala"
		_g_free0 (_tmp2_);
#line 264 "../src/MainWindow.vala"
		if (self->priv->sec >= ((guint) 60)) {
#line 827 "MainWindow.c"
			GtkLabel* _tmp3_;
			gchar* _tmp4_;
			gchar* _tmp5_;
#line 265 "../src/MainWindow.vala"
			self->priv->sec = (guint) 0;
#line 266 "../src/MainWindow.vala"
			self->priv->min = self->priv->min + 1;
#line 267 "../src/MainWindow.vala"
			_tmp3_ = self->column_time_label;
#line 267 "../src/MainWindow.vala"
			_tmp4_ = g_strdup_printf ("<span font_features='tnum'>%02u∶%02u∶%02u</span>", self->priv->hrs, self->priv->min, self->priv->sec);
#line 267 "../src/MainWindow.vala"
			_tmp5_ = _tmp4_;
#line 267 "../src/MainWindow.vala"
			gtk_label_set_label (_tmp3_, _tmp5_);
#line 267 "../src/MainWindow.vala"
			_g_free0 (_tmp5_);
#line 268 "../src/MainWindow.vala"
			if (self->priv->min >= ((guint) 60)) {
#line 847 "MainWindow.c"
				GtkLabel* _tmp6_;
				gchar* _tmp7_;
				gchar* _tmp8_;
#line 269 "../src/MainWindow.vala"
				self->priv->min = (guint) 0;
#line 270 "../src/MainWindow.vala"
				self->priv->hrs = self->priv->hrs + 1;
#line 271 "../src/MainWindow.vala"
				_tmp6_ = self->column_time_label;
#line 271 "../src/MainWindow.vala"
				_tmp7_ = g_strdup_printf ("<span font_features='tnum'>%02u∶%02u∶%02u</span>", self->priv->hrs, self->priv->min, self->priv->sec);
#line 271 "../src/MainWindow.vala"
				_tmp8_ = _tmp7_;
#line 271 "../src/MainWindow.vala"
				gtk_label_set_label (_tmp6_, _tmp8_);
#line 271 "../src/MainWindow.vala"
				_g_free0 (_tmp8_);
#line 865 "MainWindow.c"
			}
		}
	}
}

static gboolean
___lambda6_ (KhronosMainWindow* self)
{
	gboolean result = FALSE;
#line 280 "../src/MainWindow.vala"
	khronos_main_window_notification1 (self);
#line 281 "../src/MainWindow.vala"
	g_source_remove (self->priv->id2);
#line 282 "../src/MainWindow.vala"
	g_source_remove (self->priv->id3);
#line 283 "../src/MainWindow.vala"
	g_source_remove (self->priv->id4);
#line 284 "../src/MainWindow.vala"
	g_source_remove (self->priv->id5);
#line 285 "../src/MainWindow.vala"
	result = TRUE;
#line 285 "../src/MainWindow.vala"
	return result;
#line 889 "MainWindow.c"
}

static gboolean
____lambda6__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda6_ ((KhronosMainWindow*) self);
#line 279 "../src/MainWindow.vala"
	return result;
#line 899 "MainWindow.c"
}

static gboolean
___lambda7_ (KhronosMainWindow* self)
{
	gboolean result = FALSE;
#line 288 "../src/MainWindow.vala"
	khronos_main_window_notification2 (self);
#line 289 "../src/MainWindow.vala"
	g_source_remove (self->priv->id1);
#line 290 "../src/MainWindow.vala"
	g_source_remove (self->priv->id3);
#line 291 "../src/MainWindow.vala"
	g_source_remove (self->priv->id4);
#line 292 "../src/MainWindow.vala"
	g_source_remove (self->priv->id5);
#line 293 "../src/MainWindow.vala"
	result = TRUE;
#line 293 "../src/MainWindow.vala"
	return result;
#line 920 "MainWindow.c"
}

static gboolean
____lambda7__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda7_ ((KhronosMainWindow*) self);
#line 287 "../src/MainWindow.vala"
	return result;
#line 930 "MainWindow.c"
}

static gboolean
___lambda8_ (KhronosMainWindow* self)
{
	gboolean result = FALSE;
#line 296 "../src/MainWindow.vala"
	khronos_main_window_notification3 (self);
#line 297 "../src/MainWindow.vala"
	g_source_remove (self->priv->id2);
#line 298 "../src/MainWindow.vala"
	g_source_remove (self->priv->id1);
#line 299 "../src/MainWindow.vala"
	g_source_remove (self->priv->id4);
#line 300 "../src/MainWindow.vala"
	g_source_remove (self->priv->id5);
#line 301 "../src/MainWindow.vala"
	result = TRUE;
#line 301 "../src/MainWindow.vala"
	return result;
#line 951 "MainWindow.c"
}

static gboolean
____lambda8__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda8_ ((KhronosMainWindow*) self);
#line 295 "../src/MainWindow.vala"
	return result;
#line 961 "MainWindow.c"
}

static gboolean
___lambda9_ (KhronosMainWindow* self)
{
	gboolean result = FALSE;
#line 304 "../src/MainWindow.vala"
	khronos_main_window_notification4 (self);
#line 305 "../src/MainWindow.vala"
	g_source_remove (self->priv->id2);
#line 306 "../src/MainWindow.vala"
	g_source_remove (self->priv->id1);
#line 307 "../src/MainWindow.vala"
	g_source_remove (self->priv->id3);
#line 308 "../src/MainWindow.vala"
	g_source_remove (self->priv->id5);
#line 309 "../src/MainWindow.vala"
	result = TRUE;
#line 309 "../src/MainWindow.vala"
	return result;
#line 982 "MainWindow.c"
}

static gboolean
____lambda9__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda9_ ((KhronosMainWindow*) self);
#line 303 "../src/MainWindow.vala"
	return result;
#line 992 "MainWindow.c"
}

static gboolean
___lambda10_ (KhronosMainWindow* self)
{
	gboolean result = FALSE;
#line 312 "../src/MainWindow.vala"
	khronos_main_window_notification5 (self);
#line 313 "../src/MainWindow.vala"
	g_source_remove (self->priv->id1);
#line 314 "../src/MainWindow.vala"
	g_source_remove (self->priv->id2);
#line 315 "../src/MainWindow.vala"
	g_source_remove (self->priv->id3);
#line 316 "../src/MainWindow.vala"
	g_source_remove (self->priv->id4);
#line 317 "../src/MainWindow.vala"
	result = TRUE;
#line 317 "../src/MainWindow.vala"
	return result;
#line 1013 "MainWindow.c"
}

static gboolean
____lambda10__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda10_ ((KhronosMainWindow*) self);
#line 311 "../src/MainWindow.vala"
	return result;
#line 1023 "MainWindow.c"
}

void
khronos_main_window_set_timeouts (KhronosMainWindow* self)
{
#line 277 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 278 "../src/MainWindow.vala"
	if (self->start) {
#line 1033 "MainWindow.c"
		GSettings* _tmp0_;
		GSettings* _tmp1_;
		GSettings* _tmp2_;
		GSettings* _tmp3_;
		GSettings* _tmp4_;
#line 279 "../src/MainWindow.vala"
		_tmp0_ = khronos_application_gsettings;
#line 279 "../src/MainWindow.vala"
		self->priv->id1 = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) g_settings_get_int (_tmp0_, "notification-delay"), ____lambda6__gsource_func, g_object_ref (self), g_object_unref);
#line 287 "../src/MainWindow.vala"
		_tmp1_ = khronos_application_gsettings;
#line 287 "../src/MainWindow.vala"
		self->priv->id2 = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) ((gint) floor (g_settings_get_int (_tmp1_, "notification-delay") * 1.5)), ____lambda7__gsource_func, g_object_ref (self), g_object_unref);
#line 295 "../src/MainWindow.vala"
		_tmp2_ = khronos_application_gsettings;
#line 295 "../src/MainWindow.vala"
		self->priv->id3 = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) (g_settings_get_int (_tmp2_, "notification-delay") * 2), ____lambda8__gsource_func, g_object_ref (self), g_object_unref);
#line 303 "../src/MainWindow.vala"
		_tmp3_ = khronos_application_gsettings;
#line 303 "../src/MainWindow.vala"
		self->priv->id4 = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) ((gint) floor (g_settings_get_int (_tmp3_, "notification-delay") * 2.5)), ____lambda9__gsource_func, g_object_ref (self), g_object_unref);
#line 311 "../src/MainWindow.vala"
		_tmp4_ = khronos_application_gsettings;
#line 311 "../src/MainWindow.vala"
		self->priv->id5 = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) (g_settings_get_int (_tmp4_, "notification-delay") * 3), ____lambda10__gsource_func, g_object_ref (self), g_object_unref);
#line 1059 "MainWindow.c"
	}
}

void
khronos_main_window_notification1 (KhronosMainWindow* self)
{
	GNotification* notification1 = NULL;
	GSettings* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GNotification* _tmp3_;
	GNotification* _tmp4_;
	GThemedIcon* icon = NULL;
	GThemedIcon* _tmp5_;
	GtkApplication* _tmp6_;
	GtkApplication* _tmp7_;
#line 322 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 323 "../src/MainWindow.vala"
	_tmp0_ = khronos_application_gsettings;
#line 323 "../src/MainWindow.vala"
	_tmp1_ = g_strdup_printf ("%i minutes have passed", g_settings_get_int (_tmp0_, "notification-delay"));
#line 323 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 323 "../src/MainWindow.vala"
	_tmp3_ = g_notification_new (_tmp2_);
#line 323 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 323 "../src/MainWindow.vala"
	_g_free0 (_tmp2_);
#line 323 "../src/MainWindow.vala"
	notification1 = _tmp4_;
#line 324 "../src/MainWindow.vala"
	g_notification_set_body (notification1, _ ("Go rest for a while before continuing."));
#line 325 "../src/MainWindow.vala"
	_tmp5_ = (GThemedIcon*) g_themed_icon_new ("appointment-symbolic");
#line 325 "../src/MainWindow.vala"
	icon = _tmp5_;
#line 326 "../src/MainWindow.vala"
	g_notification_set_icon (notification1, (GIcon*) icon);
#line 328 "../src/MainWindow.vala"
	_tmp6_ = gtk_window_get_application ((GtkWindow*) self);
#line 328 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_;
#line 328 "../src/MainWindow.vala"
	g_application_send_notification ((GApplication*) _tmp7_, "io.github.lainsce.Khronos", notification1);
#line 322 "../src/MainWindow.vala"
	_g_object_unref0 (icon);
#line 322 "../src/MainWindow.vala"
	_g_object_unref0 (notification1);
#line 1110 "MainWindow.c"
}

void
khronos_main_window_notification2 (KhronosMainWindow* self)
{
	GNotification* notification2 = NULL;
	GSettings* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GNotification* _tmp3_;
	GNotification* _tmp4_;
	GThemedIcon* icon = NULL;
	GThemedIcon* _tmp5_;
	GtkApplication* _tmp6_;
	GtkApplication* _tmp7_;
#line 331 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 332 "../src/MainWindow.vala"
	_tmp0_ = khronos_application_gsettings;
#line 332 "../src/MainWindow.vala"
	_tmp1_ = g_strdup_printf ("%i minutes have passed", (gint) floor (g_settings_get_int (_tmp0_, "notification-delay") * 1.5));
#line 332 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 332 "../src/MainWindow.vala"
	_tmp3_ = g_notification_new (_tmp2_);
#line 332 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 332 "../src/MainWindow.vala"
	_g_free0 (_tmp2_);
#line 332 "../src/MainWindow.vala"
	notification2 = _tmp4_;
#line 333 "../src/MainWindow.vala"
	g_notification_set_body (notification2, _ ("Go rest for a while before continuing."));
#line 334 "../src/MainWindow.vala"
	_tmp5_ = (GThemedIcon*) g_themed_icon_new ("appointment-symbolic");
#line 334 "../src/MainWindow.vala"
	icon = _tmp5_;
#line 335 "../src/MainWindow.vala"
	g_notification_set_icon (notification2, (GIcon*) icon);
#line 337 "../src/MainWindow.vala"
	_tmp6_ = gtk_window_get_application ((GtkWindow*) self);
#line 337 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_;
#line 337 "../src/MainWindow.vala"
	g_application_send_notification ((GApplication*) _tmp7_, "io.github.lainsce.Khronos", notification2);
#line 331 "../src/MainWindow.vala"
	_g_object_unref0 (icon);
#line 331 "../src/MainWindow.vala"
	_g_object_unref0 (notification2);
#line 1160 "MainWindow.c"
}

void
khronos_main_window_notification3 (KhronosMainWindow* self)
{
	GNotification* notification3 = NULL;
	GSettings* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GNotification* _tmp3_;
	GNotification* _tmp4_;
	GThemedIcon* icon = NULL;
	GThemedIcon* _tmp5_;
	GtkApplication* _tmp6_;
	GtkApplication* _tmp7_;
#line 340 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 341 "../src/MainWindow.vala"
	_tmp0_ = khronos_application_gsettings;
#line 341 "../src/MainWindow.vala"
	_tmp1_ = g_strdup_printf ("%i minutes have passed", g_settings_get_int (_tmp0_, "notification-delay") * 2);
#line 341 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 341 "../src/MainWindow.vala"
	_tmp3_ = g_notification_new (_tmp2_);
#line 341 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 341 "../src/MainWindow.vala"
	_g_free0 (_tmp2_);
#line 341 "../src/MainWindow.vala"
	notification3 = _tmp4_;
#line 342 "../src/MainWindow.vala"
	g_notification_set_body (notification3, _ ("Go rest for a while before continuing."));
#line 343 "../src/MainWindow.vala"
	_tmp5_ = (GThemedIcon*) g_themed_icon_new ("appointment-symbolic");
#line 343 "../src/MainWindow.vala"
	icon = _tmp5_;
#line 344 "../src/MainWindow.vala"
	g_notification_set_icon (notification3, (GIcon*) icon);
#line 346 "../src/MainWindow.vala"
	_tmp6_ = gtk_window_get_application ((GtkWindow*) self);
#line 346 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_;
#line 346 "../src/MainWindow.vala"
	g_application_send_notification ((GApplication*) _tmp7_, "io.github.lainsce.Khronos", notification3);
#line 340 "../src/MainWindow.vala"
	_g_object_unref0 (icon);
#line 340 "../src/MainWindow.vala"
	_g_object_unref0 (notification3);
#line 1210 "MainWindow.c"
}

void
khronos_main_window_notification4 (KhronosMainWindow* self)
{
	GNotification* notification4 = NULL;
	GSettings* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GNotification* _tmp3_;
	GNotification* _tmp4_;
	GThemedIcon* icon = NULL;
	GThemedIcon* _tmp5_;
	GtkApplication* _tmp6_;
	GtkApplication* _tmp7_;
#line 349 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 350 "../src/MainWindow.vala"
	_tmp0_ = khronos_application_gsettings;
#line 350 "../src/MainWindow.vala"
	_tmp1_ = g_strdup_printf ("%i minutes have passed", (gint) floor (g_settings_get_int (_tmp0_, "notification-delay") * 2.5));
#line 350 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 350 "../src/MainWindow.vala"
	_tmp3_ = g_notification_new (_tmp2_);
#line 350 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 350 "../src/MainWindow.vala"
	_g_free0 (_tmp2_);
#line 350 "../src/MainWindow.vala"
	notification4 = _tmp4_;
#line 351 "../src/MainWindow.vala"
	g_notification_set_body (notification4, _ ("Go rest for a while before continuing."));
#line 352 "../src/MainWindow.vala"
	_tmp5_ = (GThemedIcon*) g_themed_icon_new ("appointment-symbolic");
#line 352 "../src/MainWindow.vala"
	icon = _tmp5_;
#line 353 "../src/MainWindow.vala"
	g_notification_set_icon (notification4, (GIcon*) icon);
#line 355 "../src/MainWindow.vala"
	_tmp6_ = gtk_window_get_application ((GtkWindow*) self);
#line 355 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_;
#line 355 "../src/MainWindow.vala"
	g_application_send_notification ((GApplication*) _tmp7_, "io.github.lainsce.Khronos", notification4);
#line 349 "../src/MainWindow.vala"
	_g_object_unref0 (icon);
#line 349 "../src/MainWindow.vala"
	_g_object_unref0 (notification4);
#line 1260 "MainWindow.c"
}

void
khronos_main_window_notification5 (KhronosMainWindow* self)
{
	GNotification* notification5 = NULL;
	GSettings* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GNotification* _tmp3_;
	GNotification* _tmp4_;
	GThemedIcon* icon = NULL;
	GThemedIcon* _tmp5_;
	GtkApplication* _tmp6_;
	GtkApplication* _tmp7_;
#line 358 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 359 "../src/MainWindow.vala"
	_tmp0_ = khronos_application_gsettings;
#line 359 "../src/MainWindow.vala"
	_tmp1_ = g_strdup_printf ("%i minutes have passed", g_settings_get_int (_tmp0_, "notification-delay") * 3);
#line 359 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 359 "../src/MainWindow.vala"
	_tmp3_ = g_notification_new (_tmp2_);
#line 359 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 359 "../src/MainWindow.vala"
	_g_free0 (_tmp2_);
#line 359 "../src/MainWindow.vala"
	notification5 = _tmp4_;
#line 360 "../src/MainWindow.vala"
	g_notification_set_body (notification5, _ ("Go rest for a while before continuing."));
#line 361 "../src/MainWindow.vala"
	_tmp5_ = (GThemedIcon*) g_themed_icon_new ("appointment-symbolic");
#line 361 "../src/MainWindow.vala"
	icon = _tmp5_;
#line 362 "../src/MainWindow.vala"
	g_notification_set_icon (notification5, (GIcon*) icon);
#line 364 "../src/MainWindow.vala"
	_tmp6_ = gtk_window_get_application ((GtkWindow*) self);
#line 364 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_;
#line 364 "../src/MainWindow.vala"
	g_application_send_notification ((GApplication*) _tmp7_, "io.github.lainsce.Khronos", notification5);
#line 358 "../src/MainWindow.vala"
	_g_object_unref0 (icon);
#line 358 "../src/MainWindow.vala"
	_g_object_unref0 (notification5);
#line 1310 "MainWindow.c"
}

void
khronos_main_window_action_delete_row (KhronosMainWindow* self)
{
	guint i = 0U;
	guint n = 0U;
	GListStore* _tmp0_;
#line 367 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 368 "../src/MainWindow.vala"
	_tmp0_ = self->priv->liststore;
#line 368 "../src/MainWindow.vala"
	n = g_list_model_get_n_items ((GListModel*) _tmp0_);
#line 1325 "MainWindow.c"
	{
		gboolean _tmp1_ = FALSE;
#line 369 "../src/MainWindow.vala"
		i = (guint) 0;
#line 369 "../src/MainWindow.vala"
		_tmp1_ = TRUE;
#line 369 "../src/MainWindow.vala"
		while (TRUE) {
#line 1334 "MainWindow.c"
			GListStore* _tmp3_;
#line 369 "../src/MainWindow.vala"
			if (!_tmp1_) {
#line 1338 "MainWindow.c"
				guint _tmp2_;
#line 369 "../src/MainWindow.vala"
				_tmp2_ = i;
#line 369 "../src/MainWindow.vala"
				i = _tmp2_ + 1;
#line 1344 "MainWindow.c"
			}
#line 369 "../src/MainWindow.vala"
			_tmp1_ = FALSE;
#line 369 "../src/MainWindow.vala"
			if (!(i < n)) {
#line 369 "../src/MainWindow.vala"
				break;
#line 1352 "MainWindow.c"
			}
#line 370 "../src/MainWindow.vala"
			_tmp3_ = self->priv->liststore;
#line 370 "../src/MainWindow.vala"
			g_list_store_remove (_tmp3_, i);
#line 1358 "MainWindow.c"
		}
	}
}

void
khronos_main_window_action_export (KhronosMainWindow* self)
{
	GListStore* _tmp0_;
#line 374 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 375 "../src/MainWindow.vala"
	_tmp0_ = self->priv->liststore;
#line 375 "../src/MainWindow.vala"
	khronos_file_manager_save_as (_tmp0_, NULL, NULL);
#line 1373 "MainWindow.c"
}

void
khronos_main_window_action_prefs (KhronosMainWindow* self)
{
	KhronosPrefs* prefs = NULL;
	KhronosPrefs* _tmp0_;
	GSettings* _tmp1_;
	GSettings* _tmp2_;
	GtkSwitch* _tmp3_;
#line 378 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 379 "../src/MainWindow.vala"
	_tmp0_ = khronos_prefs_new ();
#line 379 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp0_);
#line 379 "../src/MainWindow.vala"
	prefs = _tmp0_;
#line 380 "../src/MainWindow.vala"
	gtk_widget_show ((GtkWidget*) prefs);
#line 381 "../src/MainWindow.vala"
	gtk_window_set_transient_for ((GtkWindow*) prefs, (GtkWindow*) self);
#line 382 "../src/MainWindow.vala"
	_tmp1_ = khronos_application_gsettings;
#line 382 "../src/MainWindow.vala"
	khronos_prefs_set_delay (prefs, g_settings_get_int (_tmp1_, "notification-delay") / 60);
#line 384 "../src/MainWindow.vala"
	_tmp2_ = khronos_application_gsettings;
#line 384 "../src/MainWindow.vala"
	_tmp3_ = prefs->darkmode;
#line 384 "../src/MainWindow.vala"
	g_settings_bind (_tmp2_, "dark-mode", (GObject*) _tmp3_, "active", G_SETTINGS_BIND_DEFAULT);
#line 378 "../src/MainWindow.vala"
	_g_object_unref0 (prefs);
#line 1408 "MainWindow.c"
}

void
khronos_main_window_action_about (KhronosMainWindow* self)
{
#line 388 "../src/MainWindow.vala"
	static const char COPYRIGHT[] = "Copyright \xc2\xa9 2019-2021 Paulo \"Lains\" Galardi\n";
#line 390 "../src/MainWindow.vala"
	static const gchar* AUTHORS[1] = {"Paulo \"Lains\" Galardi"};
#line 1418 "MainWindow.c"
	gchar* program_name = NULL;
	gchar* _tmp0_;
#line 387 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 394 "../src/MainWindow.vala"
	_tmp0_ = g_strconcat (NAME_PREFIX, _ ("Khronos"), NULL);
#line 394 "../src/MainWindow.vala"
	program_name = _tmp0_;
#line 395 "../src/MainWindow.vala"
	gtk_show_about_dialog ((GtkWindow*) self, "program-name", program_name, "logo-icon-name", APP_ID, "version", VERSION, "comments", _ ("Track each task\'s time in a simple inobtrusive way."), "copyright", COPYRIGHT, "authors", AUTHORS, "artists", NULL, "license-type", GTK_LICENSE_GPL_3_0, "wrap-license", FALSE, "translator-credits", _ ("translator-credits"), NULL, NULL);
#line 387 "../src/MainWindow.vala"
	_g_free0 (program_name);
#line 1431 "MainWindow.c"
}

gboolean
khronos_main_window_get_is_modified (KhronosMainWindow* self)
{
	gboolean result;
#line 53 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 53 "../src/MainWindow.vala"
	result = self->priv->_is_modified;
#line 53 "../src/MainWindow.vala"
	return result;
#line 1444 "MainWindow.c"
}

void
khronos_main_window_set_is_modified (KhronosMainWindow* self,
                                     gboolean value)
{
#line 53 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 53 "../src/MainWindow.vala"
	if (khronos_main_window_get_is_modified (self) != value) {
#line 53 "../src/MainWindow.vala"
		self->priv->_is_modified = value;
#line 53 "../src/MainWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, khronos_main_window_properties[KHRONOS_MAIN_WINDOW_IS_MODIFIED_PROPERTY]);
#line 1459 "MainWindow.c"
	}
}

GtkApplication*
khronos_main_window_get_app (KhronosMainWindow* self)
{
	GtkApplication* result;
	GtkApplication* _tmp0_;
#line 61 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 61 "../src/MainWindow.vala"
	_tmp0_ = self->priv->_app;
#line 61 "../src/MainWindow.vala"
	result = _tmp0_;
#line 61 "../src/MainWindow.vala"
	return result;
#line 1476 "MainWindow.c"
}

static void
khronos_main_window_set_app (KhronosMainWindow* self,
                             GtkApplication* value)
{
#line 61 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 61 "../src/MainWindow.vala"
	if (khronos_main_window_get_app (self) != value) {
#line 61 "../src/MainWindow.vala"
		self->priv->_app = value;
#line 61 "../src/MainWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, khronos_main_window_properties[KHRONOS_MAIN_WINDOW_APP_PROPERTY]);
#line 1491 "MainWindow.c"
	}
}

GSimpleActionGroup*
khronos_main_window_get_actions (KhronosMainWindow* self)
{
	GSimpleActionGroup* result;
	GSimpleActionGroup* _tmp0_;
#line 69 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 69 "../src/MainWindow.vala"
	_tmp0_ = self->priv->_actions;
#line 69 "../src/MainWindow.vala"
	result = _tmp0_;
#line 69 "../src/MainWindow.vala"
	return result;
#line 1508 "MainWindow.c"
}

void
khronos_main_window_set_actions (KhronosMainWindow* self,
                                 GSimpleActionGroup* value)
{
#line 69 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 69 "../src/MainWindow.vala"
	if (khronos_main_window_get_actions (self) != value) {
#line 1519 "MainWindow.c"
		GSimpleActionGroup* _tmp0_;
#line 69 "../src/MainWindow.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 69 "../src/MainWindow.vala"
		_g_object_unref0 (self->priv->_actions);
#line 69 "../src/MainWindow.vala"
		self->priv->_actions = _tmp0_;
#line 69 "../src/MainWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, khronos_main_window_properties[KHRONOS_MAIN_WINDOW_ACTIONS_PROPERTY]);
#line 1529 "MainWindow.c"
	}
}

static void
_khronos_main_window___lambda11_ (KhronosMainWindow* self)
{
	GSettings* _tmp0_;
#line 129 "../src/MainWindow.vala"
	_tmp0_ = khronos_application_gsettings;
#line 129 "../src/MainWindow.vala"
	if (g_settings_get_boolean (_tmp0_, "dark-mode")) {
#line 1541 "MainWindow.c"
		GtkSettings* _tmp1_;
#line 130 "../src/MainWindow.vala"
		_tmp1_ = gtk_settings_get_default ();
#line 130 "../src/MainWindow.vala"
		g_object_set (_tmp1_, "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 1547 "MainWindow.c"
	} else {
		GtkSettings* _tmp2_;
#line 132 "../src/MainWindow.vala"
		_tmp2_ = gtk_settings_get_default ();
#line 132 "../src/MainWindow.vala"
		g_object_set (_tmp2_, "gtk-application-prefer-dark-theme", FALSE, NULL);
#line 1554 "MainWindow.c"
	}
}

static void
__khronos_main_window___lambda11__g_settings_changed (GSettings* _sender,
                                                      const gchar* key,
                                                      gpointer self)
{
#line 128 "../src/MainWindow.vala"
	_khronos_main_window___lambda11_ ((KhronosMainWindow*) self);
#line 1565 "MainWindow.c"
}

static void
_khronos_main_window___lambda12_ (KhronosMainWindow* self,
                                  GtkListBoxRow* actrow)
{
	KhronosLogRow* row = NULL;
	GtkListBox* _tmp0_;
	GtkListBoxRow* _tmp1_;
	KhronosLogRow* _tmp2_;
	GtkEntry* _tmp3_;
	KhronosLogRow* _tmp4_;
	KhronosLog* _tmp5_;
	KhronosLog* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
#line 140 "../src/MainWindow.vala"
	g_return_if_fail (actrow != NULL);
#line 141 "../src/MainWindow.vala"
	_tmp0_ = self->column;
#line 141 "../src/MainWindow.vala"
	_tmp1_ = gtk_list_box_get_selected_row (_tmp0_);
#line 141 "../src/MainWindow.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, KHRONOS_TYPE_LOG_ROW, KhronosLogRow));
#line 141 "../src/MainWindow.vala"
	row = _tmp2_;
#line 143 "../src/MainWindow.vala"
	_tmp3_ = self->column_entry;
#line 143 "../src/MainWindow.vala"
	_tmp4_ = row;
#line 143 "../src/MainWindow.vala"
	_tmp5_ = khronos_log_row_get_log (_tmp4_);
#line 143 "../src/MainWindow.vala"
	_tmp6_ = _tmp5_;
#line 143 "../src/MainWindow.vala"
	_tmp7_ = khronos_log_get_name (_tmp6_);
#line 143 "../src/MainWindow.vala"
	_tmp8_ = _tmp7_;
#line 143 "../src/MainWindow.vala"
	gtk_editable_set_text ((GtkEditable*) _tmp3_, _tmp8_);
#line 140 "../src/MainWindow.vala"
	_g_object_unref0 (row);
#line 1608 "MainWindow.c"
}

static void
__khronos_main_window___lambda12__gtk_list_box_row_activated (GtkListBox* _sender,
                                                              GtkListBoxRow* row,
                                                              gpointer self)
{
#line 140 "../src/MainWindow.vala"
	_khronos_main_window___lambda12_ ((KhronosMainWindow*) self, row);
#line 1618 "MainWindow.c"
}

static void
_khronos_main_window___lambda13_ (KhronosMainWindow* self)
{
	KhronosLog* log = NULL;
	KhronosLog* _tmp0_;
	KhronosLog* _tmp1_;
	GtkEntry* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GDateTime* dt = NULL;
	GDateTime* _tmp5_;
	KhronosLog* _tmp6_;
	GtkLabel* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	GDateTime* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	GDateTime* _tmp15_;
	GDateTime* _tmp16_;
	GDateTime* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	GListStore* _tmp24_;
	KhronosLog* _tmp25_;
	KhronosTaskManager* _tmp26_;
	GListStore* _tmp27_;
	GtkEntry* _tmp28_;
	GtkBox* _tmp29_;
#line 147 "../src/MainWindow.vala"
	_tmp0_ = khronos_log_new ();
#line 147 "../src/MainWindow.vala"
	log = _tmp0_;
#line 148 "../src/MainWindow.vala"
	_tmp1_ = log;
#line 148 "../src/MainWindow.vala"
	_tmp2_ = self->column_entry;
#line 148 "../src/MainWindow.vala"
	_tmp3_ = gtk_editable_get_text ((GtkEditable*) _tmp2_);
#line 148 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 148 "../src/MainWindow.vala"
	khronos_log_set_name (_tmp1_, _tmp4_);
#line 150 "../src/MainWindow.vala"
	_tmp5_ = g_date_time_new_now_local ();
#line 150 "../src/MainWindow.vala"
	dt = _tmp5_;
#line 151 "../src/MainWindow.vala"
	_tmp6_ = log;
#line 151 "../src/MainWindow.vala"
	_tmp7_ = self->column_time_label;
#line 151 "../src/MainWindow.vala"
	_tmp8_ = gtk_label_get_label (_tmp7_);
#line 151 "../src/MainWindow.vala"
	_tmp9_ = _tmp8_;
#line 151 "../src/MainWindow.vala"
	_tmp10_ = dt;
#line 151 "../src/MainWindow.vala"
	_tmp11_ = g_date_time_format (_tmp10_, "%a, %d/%m %H∶%M∶%S");
#line 151 "../src/MainWindow.vala"
	_tmp12_ = _tmp11_;
#line 151 "../src/MainWindow.vala"
	_tmp13_ = g_strdup_printf ("<span font_features='tnum'>%s</span>", _tmp12_);
#line 151 "../src/MainWindow.vala"
	_tmp14_ = _tmp13_;
#line 151 "../src/MainWindow.vala"
	_tmp15_ = dt;
#line 151 "../src/MainWindow.vala"
	_tmp16_ = g_date_time_add_full (_tmp15_, 0, 0, 0, (gint) self->priv->hrs, (gint) self->priv->min, (gdouble) ((gint) self->priv->sec));
#line 151 "../src/MainWindow.vala"
	_tmp17_ = _tmp16_;
#line 151 "../src/MainWindow.vala"
	_tmp18_ = g_date_time_format (_tmp17_, "%H∶%M∶%S");
#line 151 "../src/MainWindow.vala"
	_tmp19_ = _tmp18_;
#line 151 "../src/MainWindow.vala"
	_tmp20_ = g_strdup_printf ("<span font_features='tnum'>%s</span>", _tmp19_);
#line 151 "../src/MainWindow.vala"
	_tmp21_ = _tmp20_;
#line 151 "../src/MainWindow.vala"
	_tmp22_ = g_strdup_printf ("%s\n%s - %s", _tmp9_, _tmp14_, _tmp21_);
#line 151 "../src/MainWindow.vala"
	_tmp23_ = _tmp22_;
#line 151 "../src/MainWindow.vala"
	khronos_log_set_timedate (_tmp6_, _tmp23_);
#line 151 "../src/MainWindow.vala"
	_g_free0 (_tmp23_);
#line 151 "../src/MainWindow.vala"
	_g_free0 (_tmp21_);
#line 151 "../src/MainWindow.vala"
	_g_free0 (_tmp19_);
#line 151 "../src/MainWindow.vala"
	_g_date_time_unref0 (_tmp17_);
#line 151 "../src/MainWindow.vala"
	_g_free0 (_tmp14_);
#line 151 "../src/MainWindow.vala"
	_g_free0 (_tmp12_);
#line 154 "../src/MainWindow.vala"
	_tmp24_ = self->priv->liststore;
#line 154 "../src/MainWindow.vala"
	_tmp25_ = log;
#line 154 "../src/MainWindow.vala"
	g_list_store_append (_tmp24_, (GObject*) _tmp25_);
#line 155 "../src/MainWindow.vala"
	_tmp26_ = self->tm;
#line 155 "../src/MainWindow.vala"
	_tmp27_ = self->priv->liststore;
#line 155 "../src/MainWindow.vala"
	khronos_task_manager_save_to_file (_tmp26_, _tmp27_);
#line 156 "../src/MainWindow.vala"
	khronos_main_window_reset_timer (self);
#line 157 "../src/MainWindow.vala"
	khronos_main_window_set_is_modified (self, TRUE);
#line 158 "../src/MainWindow.vala"
	_tmp28_ = self->column_entry;
#line 158 "../src/MainWindow.vala"
	gtk_editable_set_text ((GtkEditable*) _tmp28_, "");
#line 159 "../src/MainWindow.vala"
	_tmp29_ = self->placeholder;
#line 159 "../src/MainWindow.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp29_, FALSE);
#line 146 "../src/MainWindow.vala"
	_g_date_time_unref0 (dt);
#line 146 "../src/MainWindow.vala"
	_g_object_unref0 (log);
#line 1752 "MainWindow.c"
}

static void
__khronos_main_window___lambda13__gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self)
{
#line 146 "../src/MainWindow.vala"
	_khronos_main_window___lambda13_ ((KhronosMainWindow*) self);
#line 1761 "MainWindow.c"
}

static gboolean
___lambda15_ (KhronosMainWindow* self)
{
	gboolean result = FALSE;
#line 167 "../src/MainWindow.vala"
	khronos_main_window_timer (self);
#line 168 "../src/MainWindow.vala"
	result = TRUE;
#line 168 "../src/MainWindow.vala"
	return result;
#line 1774 "MainWindow.c"
}

static gboolean
____lambda15__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda15_ ((KhronosMainWindow*) self);
#line 166 "../src/MainWindow.vala"
	return result;
#line 1784 "MainWindow.c"
}

static void
_khronos_main_window___lambda14_ (KhronosMainWindow* self)
{
#line 163 "../src/MainWindow.vala"
	if (self->start != TRUE) {
#line 1792 "MainWindow.c"
		GtkButton* _tmp0_;
		GtkButton* _tmp1_;
		GtkStyleContext* _tmp2_;
		GtkButton* _tmp3_;
#line 164 "../src/MainWindow.vala"
		self->start = TRUE;
#line 166 "../src/MainWindow.vala"
		self->priv->timer_id = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, ____lambda15__gsource_func, g_object_ref (self), g_object_unref);
#line 170 "../src/MainWindow.vala"
		_tmp0_ = self->column_play_button;
#line 170 "../src/MainWindow.vala"
		gtk_button_set_label (_tmp0_, _ ("Stop Timer"));
#line 171 "../src/MainWindow.vala"
		_tmp1_ = self->column_play_button;
#line 171 "../src/MainWindow.vala"
		_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) _tmp1_);
#line 171 "../src/MainWindow.vala"
		gtk_style_context_add_class (_tmp2_, "destructive-action");
#line 172 "../src/MainWindow.vala"
		_tmp3_ = self->column_button;
#line 172 "../src/MainWindow.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp3_, FALSE);
#line 1815 "MainWindow.c"
	} else {
		GtkButton* _tmp4_;
		GtkButton* _tmp5_;
		GtkStyleContext* _tmp6_;
		GtkButton* _tmp7_;
		GtkStyleContext* _tmp8_;
		GtkButton* _tmp9_;
#line 174 "../src/MainWindow.vala"
		self->start = FALSE;
#line 175 "../src/MainWindow.vala"
		g_source_remove (self->priv->timer_id);
#line 176 "../src/MainWindow.vala"
		_tmp4_ = self->column_play_button;
#line 176 "../src/MainWindow.vala"
		gtk_button_set_label (_tmp4_, _ ("Start Timer"));
#line 177 "../src/MainWindow.vala"
		_tmp5_ = self->column_play_button;
#line 177 "../src/MainWindow.vala"
		_tmp6_ = gtk_widget_get_style_context ((GtkWidget*) _tmp5_);
#line 177 "../src/MainWindow.vala"
		gtk_style_context_remove_class (_tmp6_, "destructive-action");
#line 178 "../src/MainWindow.vala"
		_tmp7_ = self->column_play_button;
#line 178 "../src/MainWindow.vala"
		_tmp8_ = gtk_widget_get_style_context ((GtkWidget*) _tmp7_);
#line 178 "../src/MainWindow.vala"
		gtk_style_context_add_class (_tmp8_, "suggested-action");
#line 179 "../src/MainWindow.vala"
		_tmp9_ = self->column_button;
#line 179 "../src/MainWindow.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp9_, TRUE);
#line 1847 "MainWindow.c"
	}
}

static void
__khronos_main_window___lambda14__gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self)
{
#line 162 "../src/MainWindow.vala"
	_khronos_main_window___lambda14_ ((KhronosMainWindow*) self);
#line 1857 "MainWindow.c"
}

static void
_khronos_main_window___lambda16_ (KhronosMainWindow* self)
{
	GtkEntry* _tmp0_;
	guint _tmp1_;
	guint _tmp2_;
	GtkListBox* _tmp5_;
#line 184 "../src/MainWindow.vala"
	_tmp0_ = self->column_entry;
#line 184 "../src/MainWindow.vala"
	_tmp1_ = gtk_entry_get_text_length (_tmp0_);
#line 184 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 184 "../src/MainWindow.vala"
	if (_tmp2_ != ((guint) 0)) {
#line 1875 "MainWindow.c"
		GtkButton* _tmp3_;
#line 185 "../src/MainWindow.vala"
		_tmp3_ = self->column_play_button;
#line 185 "../src/MainWindow.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp3_, TRUE);
#line 1881 "MainWindow.c"
	} else {
		GtkButton* _tmp4_;
#line 187 "../src/MainWindow.vala"
		_tmp4_ = self->column_play_button;
#line 187 "../src/MainWindow.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp4_, FALSE);
#line 1888 "MainWindow.c"
	}
#line 189 "../src/MainWindow.vala"
	_tmp5_ = self->column;
#line 189 "../src/MainWindow.vala"
	gtk_list_box_unselect_all (_tmp5_);
#line 1894 "MainWindow.c"
}

static void
__khronos_main_window___lambda16__gtk_editable_changed (GtkEditable* _sender,
                                                        gpointer self)
{
#line 183 "../src/MainWindow.vala"
	_khronos_main_window___lambda16_ ((KhronosMainWindow*) self);
#line 1903 "MainWindow.c"
}

static void
_khronos_main_window___lambda17_ (KhronosMainWindow* self)
{
	GtkStack* _tmp0_;
	const gchar* _tmp1_;
#line 193 "../src/MainWindow.vala"
	_tmp0_ = self->win_stack;
#line 193 "../src/MainWindow.vala"
	_tmp1_ = gtk_stack_get_visible_child_name (_tmp0_);
#line 193 "../src/MainWindow.vala"
	if (g_strcmp0 (_tmp1_, "main") == 0) {
#line 1917 "MainWindow.c"
		GtkStack* _tmp2_;
#line 194 "../src/MainWindow.vala"
		_tmp2_ = self->title_stack;
#line 194 "../src/MainWindow.vala"
		gtk_stack_set_visible_child_name (_tmp2_, "main_title");
#line 1923 "MainWindow.c"
	} else {
		GtkStack* _tmp3_;
#line 196 "../src/MainWindow.vala"
		_tmp3_ = self->title_stack;
#line 196 "../src/MainWindow.vala"
		gtk_stack_set_visible_child_name (_tmp3_, "logs_title");
#line 1930 "MainWindow.c"
	}
}

static void
__khronos_main_window___lambda17__g_object_notify (GObject* _sender,
                                                   GParamSpec* pspec,
                                                   gpointer self)
{
#line 192 "../src/MainWindow.vala"
	_khronos_main_window___lambda17_ ((KhronosMainWindow*) self);
#line 1941 "MainWindow.c"
}

static void
_khronos_main_window___lambda18_ (KhronosMainWindow* self)
{
	GListStore* _tmp0_;
	GtkBox* _tmp1_;
#line 205 "../src/MainWindow.vala"
	_tmp0_ = self->priv->liststore;
#line 205 "../src/MainWindow.vala"
	g_list_store_remove_all (_tmp0_);
#line 206 "../src/MainWindow.vala"
	_tmp1_ = self->placeholder;
#line 206 "../src/MainWindow.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp1_, TRUE);
#line 1957 "MainWindow.c"
}

static void
__khronos_main_window___lambda18__gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self)
{
#line 204 "../src/MainWindow.vala"
	_khronos_main_window___lambda18_ ((KhronosMainWindow*) self);
#line 1966 "MainWindow.c"
}

static void
_khronos_main_window___lambda19_ (KhronosMainWindow* self)
{
	KhronosTaskManager* _tmp0_;
	GListStore* _tmp1_;
	GListStore* _tmp2_;
#line 218 "../src/MainWindow.vala"
	_tmp0_ = self->tm;
#line 218 "../src/MainWindow.vala"
	_tmp1_ = self->priv->liststore;
#line 218 "../src/MainWindow.vala"
	khronos_task_manager_save_to_file (_tmp0_, _tmp1_);
#line 220 "../src/MainWindow.vala"
	_tmp2_ = self->priv->liststore;
#line 220 "../src/MainWindow.vala"
	if (g_list_model_get_n_items ((GListModel*) _tmp2_) == ((guint) 0)) {
#line 1985 "MainWindow.c"
		GtkBox* _tmp3_;
#line 221 "../src/MainWindow.vala"
		_tmp3_ = self->placeholder;
#line 221 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp3_, TRUE);
#line 1991 "MainWindow.c"
	}
}

static void
__khronos_main_window___lambda19__g_list_model_items_changed (GListModel* _sender,
                                                              guint position,
                                                              guint removed,
                                                              guint added,
                                                              gpointer self)
{
#line 217 "../src/MainWindow.vala"
	_khronos_main_window___lambda19_ ((KhronosMainWindow*) self);
#line 2004 "MainWindow.c"
}

static GObject *
khronos_main_window_constructor (GType type,
                                 guint n_construct_properties,
                                 GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	KhronosMainWindow * self;
	KhronosTaskManager* _tmp0_;
	GSettings* _tmp1_;
	GListStore* _tmp2_;
	GtkLabel* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GtkListBox* _tmp6_;
	GtkButton* _tmp7_;
	GtkButton* _tmp8_;
	GtkEntry* _tmp9_;
	GtkStack* _tmp10_;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp11_;
	GtkMenuButton* _tmp12_;
	GtkBuilder* _tmp13_;
	GObject* _tmp14_;
	GtkMenuButton* _tmp15_;
	GtkBuilder* _tmp16_;
	GObject* _tmp17_;
	GtkButton* _tmp18_;
	KhronosTaskManager* _tmp19_;
	GListStore* _tmp20_;
#line 124 "../src/MainWindow.vala"
	parent_class = G_OBJECT_CLASS (khronos_main_window_parent_class);
#line 124 "../src/MainWindow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 124 "../src/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindow);
#line 125 "../src/MainWindow.vala"
	adw_init ();
#line 126 "../src/MainWindow.vala"
	_tmp0_ = khronos_task_manager_new (self);
#line 126 "../src/MainWindow.vala"
	_khronos_task_manager_unref0 (self->tm);
#line 126 "../src/MainWindow.vala"
	self->tm = _tmp0_;
#line 128 "../src/MainWindow.vala"
	_tmp1_ = khronos_application_gsettings;
#line 128 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp1_, "changed", (GCallback) __khronos_main_window___lambda11__g_settings_changed, self, 0);
#line 136 "../src/MainWindow.vala"
	_tmp2_ = g_list_store_new (KHRONOS_TYPE_LOG);
#line 136 "../src/MainWindow.vala"
	_g_object_unref0 (self->priv->liststore);
#line 136 "../src/MainWindow.vala"
	self->priv->liststore = _tmp2_;
#line 138 "../src/MainWindow.vala"
	_tmp3_ = self->column_time_label;
#line 138 "../src/MainWindow.vala"
	_tmp4_ = g_strdup_printf ("<span font_features='tnum'>%02u∶%02u∶%02u</span>", self->priv->hrs, self->priv->min, self->priv->sec);
#line 138 "../src/MainWindow.vala"
	_tmp5_ = _tmp4_;
#line 138 "../src/MainWindow.vala"
	gtk_label_set_label (_tmp3_, _tmp5_);
#line 138 "../src/MainWindow.vala"
	_g_free0 (_tmp5_);
#line 140 "../src/MainWindow.vala"
	_tmp6_ = self->column;
#line 140 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp6_, "row-activated", (GCallback) __khronos_main_window___lambda12__gtk_list_box_row_activated, self, 0);
#line 146 "../src/MainWindow.vala"
	_tmp7_ = self->column_button;
#line 146 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp7_, "clicked", (GCallback) __khronos_main_window___lambda13__gtk_button_clicked, self, 0);
#line 162 "../src/MainWindow.vala"
	_tmp8_ = self->column_play_button;
#line 162 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp8_, "clicked", (GCallback) __khronos_main_window___lambda14__gtk_button_clicked, self, 0);
#line 183 "../src/MainWindow.vala"
	_tmp9_ = self->column_entry;
#line 183 "../src/MainWindow.vala"
	g_signal_connect_object ((GtkEditable*) _tmp9_, "changed", (GCallback) __khronos_main_window___lambda16__gtk_editable_changed, self, 0);
#line 192 "../src/MainWindow.vala"
	_tmp10_ = self->win_stack;
#line 192 "../src/MainWindow.vala"
	g_signal_connect_object ((GObject*) _tmp10_, "notify::visible-child-name", (GCallback) __khronos_main_window___lambda17__g_object_notify, self, 0);
#line 200 "../src/MainWindow.vala"
	_tmp11_ = gtk_builder_new_from_resource ("/io/github/lainsce/Khronos/mainmenu.ui");
#line 200 "../src/MainWindow.vala"
	builder = _tmp11_;
#line 201 "../src/MainWindow.vala"
	_tmp12_ = self->menu_button;
#line 201 "../src/MainWindow.vala"
	_tmp13_ = builder;
#line 201 "../src/MainWindow.vala"
	_tmp14_ = gtk_builder_get_object (_tmp13_, "menu");
#line 201 "../src/MainWindow.vala"
	gtk_menu_button_set_menu_model (_tmp12_, G_TYPE_CHECK_INSTANCE_CAST (_tmp14_, g_menu_model_get_type (), GMenuModel));
#line 202 "../src/MainWindow.vala"
	_tmp15_ = self->menu_button2;
#line 202 "../src/MainWindow.vala"
	_tmp16_ = builder;
#line 202 "../src/MainWindow.vala"
	_tmp17_ = gtk_builder_get_object (_tmp16_, "menu");
#line 202 "../src/MainWindow.vala"
	gtk_menu_button_set_menu_model (_tmp15_, G_TYPE_CHECK_INSTANCE_CAST (_tmp17_, g_menu_model_get_type (), GMenuModel));
#line 204 "../src/MainWindow.vala"
	_tmp18_ = self->trash_button;
#line 204 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp18_, "clicked", (GCallback) __khronos_main_window___lambda18__gtk_button_clicked, self, 0);
#line 209 "../src/MainWindow.vala"
	_tmp19_ = self->tm;
#line 209 "../src/MainWindow.vala"
	khronos_task_manager_load_from_file (_tmp19_);
#line 211 "../src/MainWindow.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, 360, 360);
#line 212 "../src/MainWindow.vala"
	gtk_widget_show ((GtkWidget*) self);
#line 213 "../src/MainWindow.vala"
	gtk_window_present ((GtkWindow*) self);
#line 215 "../src/MainWindow.vala"
	khronos_main_window_set_timeouts (self);
#line 216 "../src/MainWindow.vala"
	khronos_main_window_listen_to_changes (self);
#line 217 "../src/MainWindow.vala"
	_tmp20_ = self->priv->liststore;
#line 217 "../src/MainWindow.vala"
	g_signal_connect_object ((GListModel*) _tmp20_, "items-changed", (GCallback) __khronos_main_window___lambda19__g_list_model_items_changed, self, 0);
#line 124 "../src/MainWindow.vala"
	_g_object_unref0 (builder);
#line 124 "../src/MainWindow.vala"
	return obj;
#line 2137 "MainWindow.c"
}

static void
khronos_main_window_class_init (KhronosMainWindowClass * klass,
                                gpointer klass_data)
{
	GeeHashMultiMap* _tmp0_;
#line 21 "../src/MainWindow.vala"
	khronos_main_window_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/MainWindow.vala"
	g_type_class_adjust_private_offset (klass, &KhronosMainWindow_private_offset);
#line 21 "../src/MainWindow.vala"
	((GtkWindowClass *) klass)->close_request = (gboolean (*) (GtkWindow*)) khronos_main_window_real_close_request;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_khronos_main_window_get_property;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_khronos_main_window_set_property;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->constructor = khronos_main_window_constructor;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = khronos_main_window_finalize;
#line 21 "../src/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), KHRONOS_MAIN_WINDOW_IS_MODIFIED_PROPERTY, khronos_main_window_properties[KHRONOS_MAIN_WINDOW_IS_MODIFIED_PROPERTY] = g_param_spec_boolean ("is-modified", "is-modified", "is-modified", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 21 "../src/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), KHRONOS_MAIN_WINDOW_APP_PROPERTY, khronos_main_window_properties[KHRONOS_MAIN_WINDOW_APP_PROPERTY] = g_param_spec_object ("app", "app", "app", gtk_application_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 21 "../src/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), KHRONOS_MAIN_WINDOW_ACTIONS_PROPERTY, khronos_main_window_properties[KHRONOS_MAIN_WINDOW_ACTIONS_PROPERTY] = g_param_spec_object ("actions", "actions", "actions", g_simple_action_group_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/lainsce/Khronos/main_window.ui");
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "column", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, column));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "column_entry", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, column_entry));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "column_time_label", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, column_time_label));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "column_button", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, column_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "column_play_button", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, column_play_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu_button", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, menu_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "trash_button", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, trash_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu_button2", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, menu_button2));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "win_switcher", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, win_switcher));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "win_switcher2", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, win_switcher2));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "title_stack", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, title_stack));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "win_stack", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, win_stack));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "placeholder", FALSE, G_STRUCT_OFFSET (KhronosMainWindow, placeholder));
#line 75 "../src/MainWindow.vala"
	_tmp0_ = gee_hash_multi_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 75 "../src/MainWindow.vala"
	khronos_main_window_action_accelerators = (GeeMultiMap*) _tmp0_;
#line 2197 "MainWindow.c"
}

static void
khronos_main_window_instance_init (KhronosMainWindow * self,
                                   gpointer klass)
{
#line 21 "../src/MainWindow.vala"
	self->priv = khronos_main_window_get_instance_private (self);
#line 53 "../src/MainWindow.vala"
	self->priv->_is_modified = FALSE;
#line 54 "../src/MainWindow.vala"
	self->start = FALSE;
#line 56 "../src/MainWindow.vala"
	self->priv->sec = (guint) 0;
#line 57 "../src/MainWindow.vala"
	self->priv->min = (guint) 0;
#line 58 "../src/MainWindow.vala"
	self->priv->hrs = (guint) 0;
#line 63 "../src/MainWindow.vala"
	self->priv->id1 = (guint) 0;
#line 64 "../src/MainWindow.vala"
	self->priv->id2 = (guint) 0;
#line 65 "../src/MainWindow.vala"
	self->priv->id3 = (guint) 0;
#line 66 "../src/MainWindow.vala"
	self->priv->id4 = (guint) 0;
#line 67 "../src/MainWindow.vala"
	self->priv->id5 = (guint) 0;
#line 21 "../src/MainWindow.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 2228 "MainWindow.c"
}

static void
khronos_main_window_finalize (GObject * obj)
{
	KhronosMainWindow * self;
#line 21 "../src/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindow);
#line 25 "../src/MainWindow.vala"
	_g_object_unref0 (self->column);
#line 27 "../src/MainWindow.vala"
	_g_object_unref0 (self->column_entry);
#line 29 "../src/MainWindow.vala"
	_g_object_unref0 (self->column_time_label);
#line 31 "../src/MainWindow.vala"
	_g_object_unref0 (self->column_button);
#line 33 "../src/MainWindow.vala"
	_g_object_unref0 (self->column_play_button);
#line 35 "../src/MainWindow.vala"
	_g_object_unref0 (self->menu_button);
#line 37 "../src/MainWindow.vala"
	_g_object_unref0 (self->trash_button);
#line 39 "../src/MainWindow.vala"
	_g_object_unref0 (self->menu_button2);
#line 41 "../src/MainWindow.vala"
	_g_object_unref0 (self->win_switcher);
#line 43 "../src/MainWindow.vala"
	_g_object_unref0 (self->win_switcher2);
#line 45 "../src/MainWindow.vala"
	_g_object_unref0 (self->title_stack);
#line 47 "../src/MainWindow.vala"
	_g_object_unref0 (self->win_stack);
#line 49 "../src/MainWindow.vala"
	_g_object_unref0 (self->placeholder);
#line 51 "../src/MainWindow.vala"
	_g_object_unref0 (self->priv->liststore);
#line 60 "../src/MainWindow.vala"
	_khronos_task_manager_unref0 (self->tm);
#line 69 "../src/MainWindow.vala"
	_g_object_unref0 (self->priv->_actions);
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (khronos_main_window_parent_class)->finalize (obj);
#line 2271 "MainWindow.c"
}

static GType
khronos_main_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KhronosMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) khronos_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KhronosMainWindow), 0, (GInstanceInitFunc) khronos_main_window_instance_init, NULL };
	GType khronos_main_window_type_id;
	khronos_main_window_type_id = g_type_register_static (adw_application_window_get_type (), "KhronosMainWindow", &g_define_type_info, 0);
	KhronosMainWindow_private_offset = g_type_add_instance_private (khronos_main_window_type_id, sizeof (KhronosMainWindowPrivate));
	return khronos_main_window_type_id;
}

GType
khronos_main_window_get_type (void)
{
	static volatile gsize khronos_main_window_type_id__volatile = 0;
	if (g_once_init_enter (&khronos_main_window_type_id__volatile)) {
		GType khronos_main_window_type_id;
		khronos_main_window_type_id = khronos_main_window_get_type_once ();
		g_once_init_leave (&khronos_main_window_type_id__volatile, khronos_main_window_type_id);
	}
	return khronos_main_window_type_id__volatile;
}

static void
_vala_khronos_main_window_get_property (GObject * object,
                                        guint property_id,
                                        GValue * value,
                                        GParamSpec * pspec)
{
	KhronosMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindow);
#line 21 "../src/MainWindow.vala"
	switch (property_id) {
#line 21 "../src/MainWindow.vala"
		case KHRONOS_MAIN_WINDOW_IS_MODIFIED_PROPERTY:
#line 21 "../src/MainWindow.vala"
		g_value_set_boolean (value, khronos_main_window_get_is_modified (self));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case KHRONOS_MAIN_WINDOW_APP_PROPERTY:
#line 21 "../src/MainWindow.vala"
		g_value_set_object (value, khronos_main_window_get_app (self));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case KHRONOS_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 21 "../src/MainWindow.vala"
		g_value_set_object (value, khronos_main_window_get_actions (self));
#line 21 "../src/MainWindow.vala"
		break;
#line 2324 "MainWindow.c"
		default:
#line 21 "../src/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/MainWindow.vala"
		break;
#line 2330 "MainWindow.c"
	}
}

static void
_vala_khronos_main_window_set_property (GObject * object,
                                        guint property_id,
                                        const GValue * value,
                                        GParamSpec * pspec)
{
	KhronosMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, KHRONOS_TYPE_MAIN_WINDOW, KhronosMainWindow);
#line 21 "../src/MainWindow.vala"
	switch (property_id) {
#line 21 "../src/MainWindow.vala"
		case KHRONOS_MAIN_WINDOW_IS_MODIFIED_PROPERTY:
#line 21 "../src/MainWindow.vala"
		khronos_main_window_set_is_modified (self, g_value_get_boolean (value));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case KHRONOS_MAIN_WINDOW_APP_PROPERTY:
#line 21 "../src/MainWindow.vala"
		khronos_main_window_set_app (self, g_value_get_object (value));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case KHRONOS_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 21 "../src/MainWindow.vala"
		khronos_main_window_set_actions (self, g_value_get_object (value));
#line 21 "../src/MainWindow.vala"
		break;
#line 2362 "MainWindow.c"
		default:
#line 21 "../src/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/MainWindow.vala"
		break;
#line 2368 "MainWindow.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

