/* Prefs.c generated by valac 0.50.2, the Vala compiler
 * generated from Prefs.vala, do not modify */

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>

#define KHRONOS_TYPE_PREFS (khronos_prefs_get_type ())
#define KHRONOS_PREFS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KHRONOS_TYPE_PREFS, KhronosPrefs))
#define KHRONOS_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KHRONOS_TYPE_PREFS, KhronosPrefsClass))
#define KHRONOS_IS_PREFS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KHRONOS_TYPE_PREFS))
#define KHRONOS_IS_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KHRONOS_TYPE_PREFS))
#define KHRONOS_PREFS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KHRONOS_TYPE_PREFS, KhronosPrefsClass))

typedef struct _KhronosPrefs KhronosPrefs;
typedef struct _KhronosPrefsClass KhronosPrefsClass;
typedef struct _KhronosPrefsPrivate KhronosPrefsPrivate;
enum  {
	KHRONOS_PREFS_0_PROPERTY,
	KHRONOS_PREFS_DELAY_PROPERTY,
	KHRONOS_PREFS_ACTIVE_PROPERTY,
	KHRONOS_PREFS_NUM_PROPERTIES
};
static GParamSpec* khronos_prefs_properties[KHRONOS_PREFS_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _KhronosPrefs {
	AdwPreferencesWindow parent_instance;
	KhronosPrefsPrivate * priv;
	GtkSwitch* darkmode;
};

struct _KhronosPrefsClass {
	AdwPreferencesWindowClass parent_class;
};

struct _KhronosPrefsPrivate {
	gint _delay;
	gboolean _active;
};

static gint KhronosPrefs_private_offset;
static gpointer khronos_prefs_parent_class = NULL;

GType khronos_prefs_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KhronosPrefs, g_object_unref)
KhronosPrefs* khronos_prefs_new (void);
KhronosPrefs* khronos_prefs_construct (GType object_type);
gint khronos_prefs_get_delay (KhronosPrefs* self);
void khronos_prefs_set_delay (KhronosPrefs* self,
                              gint value);
gboolean khronos_prefs_get_active (KhronosPrefs* self);
void khronos_prefs_set_active (KhronosPrefs* self,
                               gboolean value);
static void khronos_prefs_finalize (GObject * obj);
static GType khronos_prefs_get_type_once (void);
static void _vala_khronos_prefs_get_property (GObject * object,
                                       guint property_id,
                                       GValue * value,
                                       GParamSpec * pspec);
static void _vala_khronos_prefs_set_property (GObject * object,
                                       guint property_id,
                                       const GValue * value,
                                       GParamSpec * pspec);

static inline gpointer
khronos_prefs_get_instance_private (KhronosPrefs* self)
{
	return G_STRUCT_MEMBER_P (self, KhronosPrefs_private_offset);
}

KhronosPrefs*
khronos_prefs_construct (GType object_type)
{
	KhronosPrefs * self = NULL;
#line 3 "../src/Prefs.vala"
	self = (KhronosPrefs*) g_object_new (object_type, NULL);
#line 3 "../src/Prefs.vala"
	return self;
#line 82 "Prefs.c"
}

KhronosPrefs*
khronos_prefs_new (void)
{
#line 3 "../src/Prefs.vala"
	return khronos_prefs_construct (KHRONOS_TYPE_PREFS);
#line 90 "Prefs.c"
}

gint
khronos_prefs_get_delay (KhronosPrefs* self)
{
	gint result;
#line 4 "../src/Prefs.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 4 "../src/Prefs.vala"
	result = self->priv->_delay;
#line 4 "../src/Prefs.vala"
	return result;
#line 103 "Prefs.c"
}

void
khronos_prefs_set_delay (KhronosPrefs* self,
                         gint value)
{
#line 4 "../src/Prefs.vala"
	g_return_if_fail (self != NULL);
#line 4 "../src/Prefs.vala"
	if (khronos_prefs_get_delay (self) != value) {
#line 4 "../src/Prefs.vala"
		self->priv->_delay = value;
#line 4 "../src/Prefs.vala"
		g_object_notify_by_pspec ((GObject *) self, khronos_prefs_properties[KHRONOS_PREFS_DELAY_PROPERTY]);
#line 118 "Prefs.c"
	}
}

gboolean
khronos_prefs_get_active (KhronosPrefs* self)
{
	gboolean result;
#line 5 "../src/Prefs.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 5 "../src/Prefs.vala"
	result = self->priv->_active;
#line 5 "../src/Prefs.vala"
	return result;
#line 132 "Prefs.c"
}

void
khronos_prefs_set_active (KhronosPrefs* self,
                          gboolean value)
{
#line 5 "../src/Prefs.vala"
	g_return_if_fail (self != NULL);
#line 5 "../src/Prefs.vala"
	if (khronos_prefs_get_active (self) != value) {
#line 5 "../src/Prefs.vala"
		self->priv->_active = value;
#line 5 "../src/Prefs.vala"
		g_object_notify_by_pspec ((GObject *) self, khronos_prefs_properties[KHRONOS_PREFS_ACTIVE_PROPERTY]);
#line 147 "Prefs.c"
	}
}

static void
khronos_prefs_class_init (KhronosPrefsClass * klass,
                          gpointer klass_data)
{
#line 3 "../src/Prefs.vala"
	khronos_prefs_parent_class = g_type_class_peek_parent (klass);
#line 3 "../src/Prefs.vala"
	g_type_class_adjust_private_offset (klass, &KhronosPrefs_private_offset);
#line 3 "../src/Prefs.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_khronos_prefs_get_property;
#line 3 "../src/Prefs.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_khronos_prefs_set_property;
#line 3 "../src/Prefs.vala"
	G_OBJECT_CLASS (klass)->finalize = khronos_prefs_finalize;
#line 3 "../src/Prefs.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), KHRONOS_PREFS_DELAY_PROPERTY, khronos_prefs_properties[KHRONOS_PREFS_DELAY_PROPERTY] = g_param_spec_int ("delay", "delay", "delay", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "../src/Prefs.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), KHRONOS_PREFS_ACTIVE_PROPERTY, khronos_prefs_properties[KHRONOS_PREFS_ACTIVE_PROPERTY] = g_param_spec_boolean ("active", "active", "active", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "../src/Prefs.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/lainsce/Khronos/prefs.ui");
#line 3 "../src/Prefs.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "darkmode", FALSE, G_STRUCT_OFFSET (KhronosPrefs, darkmode));
#line 173 "Prefs.c"
}

static void
khronos_prefs_instance_init (KhronosPrefs * self,
                             gpointer klass)
{
#line 3 "../src/Prefs.vala"
	self->priv = khronos_prefs_get_instance_private (self);
#line 3 "../src/Prefs.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 184 "Prefs.c"
}

static void
khronos_prefs_finalize (GObject * obj)
{
	KhronosPrefs * self;
#line 3 "../src/Prefs.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KHRONOS_TYPE_PREFS, KhronosPrefs);
#line 8 "../src/Prefs.vala"
	_g_object_unref0 (self->darkmode);
#line 3 "../src/Prefs.vala"
	G_OBJECT_CLASS (khronos_prefs_parent_class)->finalize (obj);
#line 197 "Prefs.c"
}

static GType
khronos_prefs_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KhronosPrefsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) khronos_prefs_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KhronosPrefs), 0, (GInstanceInitFunc) khronos_prefs_instance_init, NULL };
	GType khronos_prefs_type_id;
	khronos_prefs_type_id = g_type_register_static (adw_preferences_window_get_type (), "KhronosPrefs", &g_define_type_info, 0);
	KhronosPrefs_private_offset = g_type_add_instance_private (khronos_prefs_type_id, sizeof (KhronosPrefsPrivate));
	return khronos_prefs_type_id;
}

GType
khronos_prefs_get_type (void)
{
	static volatile gsize khronos_prefs_type_id__volatile = 0;
	if (g_once_init_enter (&khronos_prefs_type_id__volatile)) {
		GType khronos_prefs_type_id;
		khronos_prefs_type_id = khronos_prefs_get_type_once ();
		g_once_init_leave (&khronos_prefs_type_id__volatile, khronos_prefs_type_id);
	}
	return khronos_prefs_type_id__volatile;
}

static void
_vala_khronos_prefs_get_property (GObject * object,
                                  guint property_id,
                                  GValue * value,
                                  GParamSpec * pspec)
{
	KhronosPrefs * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, KHRONOS_TYPE_PREFS, KhronosPrefs);
#line 3 "../src/Prefs.vala"
	switch (property_id) {
#line 3 "../src/Prefs.vala"
		case KHRONOS_PREFS_DELAY_PROPERTY:
#line 3 "../src/Prefs.vala"
		g_value_set_int (value, khronos_prefs_get_delay (self));
#line 3 "../src/Prefs.vala"
		break;
#line 3 "../src/Prefs.vala"
		case KHRONOS_PREFS_ACTIVE_PROPERTY:
#line 3 "../src/Prefs.vala"
		g_value_set_boolean (value, khronos_prefs_get_active (self));
#line 3 "../src/Prefs.vala"
		break;
#line 244 "Prefs.c"
		default:
#line 3 "../src/Prefs.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "../src/Prefs.vala"
		break;
#line 250 "Prefs.c"
	}
}

static void
_vala_khronos_prefs_set_property (GObject * object,
                                  guint property_id,
                                  const GValue * value,
                                  GParamSpec * pspec)
{
	KhronosPrefs * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, KHRONOS_TYPE_PREFS, KhronosPrefs);
#line 3 "../src/Prefs.vala"
	switch (property_id) {
#line 3 "../src/Prefs.vala"
		case KHRONOS_PREFS_DELAY_PROPERTY:
#line 3 "../src/Prefs.vala"
		khronos_prefs_set_delay (self, g_value_get_int (value));
#line 3 "../src/Prefs.vala"
		break;
#line 3 "../src/Prefs.vala"
		case KHRONOS_PREFS_ACTIVE_PROPERTY:
#line 3 "../src/Prefs.vala"
		khronos_prefs_set_active (self, g_value_get_boolean (value));
#line 3 "../src/Prefs.vala"
		break;
#line 276 "Prefs.c"
		default:
#line 3 "../src/Prefs.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "../src/Prefs.vala"
		break;
#line 282 "Prefs.c"
	}
}

