/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APP_ID "io.github.lainsce.Khronos.Devel"

#define DATADIR "/app/share"

#define GETTEXT_PACKAGE "io.github.lainsce.Khronos"

#define GNOMELOCALEDIR "/app/share/locale"

#define G_LOG_DOMAIN "io.github.lainsce.KhronosDevel"

#define NAME_PREFIX "(Development) "

#define PACKAGE_NAME "io.github.lainsce.Khronos"

#define PACKAGE_VERSION "3.0.0"

#define PROFILE "Devel"

#define VERSION "3.0.0"

