on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak-builder:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: io.github.lainsce.Khronos.Devel.flatpak
          manifest-path: io.github.lainsce.Khronos.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          run-tests: true
